/* Reflect successful Data Hub snapshots and live imports in the open-month UI. */
(()=>{
const ENDPOINT='https://ijaqabjjhsuvovtfffit.supabase.co/functions/v1/data-ingest';
const IMPORTS_ENDPOINT='https://ijaqabjjhsuvovtfffit.supabase.co/functions/v1/imports-live';
const STORE='2w.datahub.uploadKey';
let snapshot=null,importsSnapshot=null,applying=false,lastImportsCutoff=null;
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const fmt=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:0}).format(Number(n)||0);
const p1=n=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${(Number(n)*100).toFixed(1).replace('.',',')}%`:'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function getJson(url,key){const r=await fetch(url,{headers:{'x-upload-key':key},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function refreshLive(){const key=localStorage.getItem(STORE);if(!key)return;try{const [status,imports]=await Promise.allSettled([getJson(ENDPOINT+'?action=status',key),getJson(IMPORTS_ENDPOINT,key)]);if(status.status==='fulfilled')snapshot=status.value;if(imports.status==='fulfilled')importsSnapshot=imports.value;applyLive()}catch{}}
function latestRuns(){const o={};for(const r of snapshot?.runs||[])if(!o[r.dataset]&&r.status==='success')o[r.dataset]=r;return o}
function importsExtra(){const imp=globalThis.DATA?.imports,l=imp?.latest_month;if(!l)return '';const types=l.types||[],max=Math.max(...types.map(x=>Number(x.value)||0),1);const bars=types.slice(0,8).map(x=>`<div class="bar-row"><div class="bar-label"><span>${esc(x.name)}</span><b>${fmt(x.value)}</b></div><div class="hbar"><i style="width:${Math.max(1,(Number(x.value)||0)/max*100)}%"></i></div></div>`).join('');const insights=(imp.executive_insights||[]).map((x,i)=>`<div class="intel-row"><div><span class="badge ${i===0?'amber':'green'}">${String(i+1).padStart(2,'0')}</span><b>${esc(x)}</b></div></div>`).join('');return `<section id="live-imports-analysis"><section class="kpis"><article class="kpi" style="--accent:#b97916"><div class="kpi-top"><span>IMPORT AGO</span><em>LIVE</em></div><b>${fmt(l.total)}</b><small>${p1(l.mom)} vs Jul</small></article><article class="kpi" style="--accent:#e0182d"><div class="kpi-top"><span>HONDA SHARE IMPORT</span></div><b>${Number(l.shares?.honda||0).toFixed(1).replace('.',',')}%</b><small>volumen importado de agosto</small></article><article class="kpi" style="--accent:#18845b"><div class="kpi-top"><span>ORIGEN CHINA</span></div><b>${Number(l.shares?.china||0).toFixed(1).replace('.',',')}%</b><small>del flujo de agosto</small></article><article class="kpi" style="--accent:#2b69c9"><div class="kpi-top"><span>IKD</span></div><b>${Number(l.shares?.ikd||0).toFixed(1).replace('.',',')}%</b><small>abastecimiento para ensamble</small></article><article class="kpi" style="--accent:#8a5bd1"><div class="kpi-top"><span>ELÉCTRICOS</span></div><b>${Number(l.shares?.electrics||0).toFixed(1).replace('.',',')}%</b><small>CBU + SKD de agosto</small></article></section><div class="grid two"><section class="card"><div class="card-head"><div><span class="eyebrow">RÉGIMEN · AGOSTO</span><h2>Cómo está entrando la oferta</h2><p>IKD / CKD / SKD / CBU y eléctricos. Señal de supply, no demanda.</p></div></div><div class="bars">${bars}</div></section><section class="card"><div class="card-head"><div><span class="eyebrow">EXECUTIVE READ</span><h2>Qué dice la importación</h2><p>Lectura automática del último mes cargado.</p></div></div><div class="signal-list">${insights}</div></section></div></section>`}
function applyImportsUI(){const content=document.getElementById('content');if(!content||globalThis.state?.view!=='imports')return;document.getElementById('live-imports-analysis')?.remove();const html=importsExtra();if(html)content.insertAdjacentHTML('beforeend',html)}
function applyLive(){if(applying)return;applying=true;try{const runs=latestRuns(),daily=snapshot?.daily||[],last=daily[0],period=last?.period,total=daily.filter(x=>x.period===period).reduce((a,b)=>a+Number(b.market_total||0),0);document.querySelectorAll('.update-band>div').forEach(d=>{const l=norm(d.querySelector('span')?.textContent),b=d.querySelector('b');if(!b)return;if(l==='SIOMAA'&&(runs.daily||last))b.textContent=runs.daily?.source_date||last?.market_date||'OK';if(l==='IMPORTS'&&(importsSnapshot?.meta_patch?.imports_cutoff||runs.imports))b.textContent=importsSnapshot?.meta_patch?.imports_cutoff||runs.imports?.source_date||runs.imports?.finished_at?.slice(0,10)||'OK'});if(total&&period){document.querySelectorAll('.kpi').forEach(k=>{const t=norm(k.querySelector('.kpi-top span')?.textContent);if(t==='NOWCAST'){const b=k.querySelector(':scope>b'),small=k.querySelector('small'),em=k.querySelector('.kpi-top em');if(b)b.textContent=fmt(total);if(small)small.textContent=`SIOMAA MTD · ${period} · corte ${last?.market_date||'—'}`;if(em){em.textContent='OPEN MONTH';em.style.opacity='1'}}})}if(importsSnapshot?.imports&&globalThis.DATA){const cutoff=importsSnapshot.meta_patch?.imports_cutoff||importsSnapshot.imports.cutoff;const changed=cutoff&&cutoff!==lastImportsCutoff;globalThis.DATA.imports=importsSnapshot.imports;globalThis.DATA.meta={...(globalThis.DATA.meta||{}),...(importsSnapshot.meta_patch||{})};lastImportsCutoff=cutoff;if(changed&&globalThis.state?.view==='imports'&&typeof globalThis.render==='function'){globalThis.render();queueMicrotask(applyImportsUI);return}}applyImportsUI()}finally{applying=false}}
function watch(){const content=document.getElementById('content');if(content)new MutationObserver(()=>queueMicrotask(applyLive)).observe(content,{childList:true,subtree:false});document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(refreshLive,500));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshLive()});document.addEventListener('click',e=>{if(e.target?.id==='dataHubConfirm')setTimeout(refreshLive,2200)},true);new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes||[]){if(n.nodeType===1&&n.id==='datahub'){const msg=n.querySelector('#dataHubMessage');if(msg)new MutationObserver(()=>{if(/carga confirmada/i.test(msg.textContent||''))refreshLive()}).observe(msg,{childList:true,subtree:true,characterData:true})}}}).observe(document.body,{childList:true,subtree:true});setTimeout(refreshLive,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();