/* Reflect successful Data Hub snapshots and live imports in the open-month UI. */
(()=>{
const ENDPOINT='https://ijaqabjjhsuvovtfffit.supabase.co/functions/v1/data-ingest';
const IMPORTS_ENDPOINT='https://ijaqabjjhsuvovtfffit.supabase.co/functions/v1/imports-live';
const STORE='2w.datahub.uploadKey';
let snapshot=null,importsSnapshot=null,applying=false,lastImportsCutoff=null;
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const fmt=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:0}).format(Number(n)||0);
async function getJson(url,key){const r=await fetch(url,{headers:{'x-upload-key':key},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function refreshLive(){const key=localStorage.getItem(STORE);if(!key)return;try{const [status,imports]=await Promise.allSettled([getJson(ENDPOINT+'?action=status',key),getJson(IMPORTS_ENDPOINT,key)]);if(status.status==='fulfilled')snapshot=status.value;if(imports.status==='fulfilled')importsSnapshot=imports.value;applyLive()}catch{}}
function latestRuns(){const o={};for(const r of snapshot?.runs||[])if(!o[r.dataset]&&r.status==='success')o[r.dataset]=r;return o}
function applyLive(){if(applying)return;applying=true;try{const runs=latestRuns(),daily=snapshot?.daily||[],last=daily[0],period=last?.period,total=daily.filter(x=>x.period===period).reduce((a,b)=>a+Number(b.market_total||0),0);document.querySelectorAll('.update-band>div').forEach(d=>{const l=norm(d.querySelector('span')?.textContent),b=d.querySelector('b');if(!b)return;if(l==='SIOMAA'&&(runs.daily||last))b.textContent=runs.daily?.source_date||last?.market_date||'OK';if(l==='IMPORTS'&&(importsSnapshot?.meta_patch?.imports_cutoff||runs.imports))b.textContent=importsSnapshot?.meta_patch?.imports_cutoff||runs.imports?.source_date||runs.imports?.finished_at?.slice(0,10)||'OK'});if(total&&period){document.querySelectorAll('.kpi').forEach(k=>{const t=norm(k.querySelector('.kpi-top span')?.textContent);if(t==='NOWCAST'){const b=k.querySelector(':scope>b'),small=k.querySelector('small'),em=k.querySelector('.kpi-top em');if(b)b.textContent=fmt(total);if(small)small.textContent=`SIOMAA MTD · ${period} · corte ${last?.market_date||'—'}`;if(em){em.textContent='OPEN MONTH';em.style.opacity='1'}}})}if(importsSnapshot?.imports&&globalThis.DATA){const cutoff=importsSnapshot.meta_patch?.imports_cutoff||importsSnapshot.imports.cutoff;const changed=cutoff&&cutoff!==lastImportsCutoff;globalThis.DATA.imports=importsSnapshot.imports;globalThis.DATA.meta={...(globalThis.DATA.meta||{}),...(importsSnapshot.meta_patch||{})};lastImportsCutoff=cutoff;if(changed&&globalThis.state?.view==='imports'&&typeof globalThis.render==='function'){globalThis.render();return}}}finally{applying=false}}
function watch(){document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(refreshLive,500));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshLive()});document.addEventListener('click',e=>{if(e.target?.id==='dataHubConfirm')setTimeout(refreshLive,2200)},true);new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes||[]){if(n.nodeType===1&&n.id==='datahub'){const msg=n.querySelector('#dataHubMessage');if(msg)new MutationObserver(()=>{if(/carga confirmada/i.test(msg.textContent||''))refreshLive()}).observe(msg,{childList:true,subtree:true,characterData:true})}}}).observe(document.body,{childList:true,subtree:true});setTimeout(refreshLive,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();