/* Governed Data Hub: XLS/XLSX/CSV -> Supabase ingestion */
(()=>{
const ENDPOINT='https://ijaqabjjhsuvovtfffit.supabase.co/functions/v1/data-ingest';
const STORE_KEY='2w.datahub.uploadKey';
const CHUNK=500;
let parsed=null,fileMeta=null,busy=false,lastStatus=null,io=null;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim();if(!s)return 0;s=s.replace(/\s/g,'');if(/^[-+]?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else if(/^[-+]?\d+(,\d+)$/.test(s))s=s.replace(',','.');else s=s.replace(/,/g,'');const n=Number(s);return Number.isFinite(n)?n:0};
const brands=['ROYAL ENFIELD','HARLEY DAVIDSON','CFMOTO','KAWASAKI','HUSQVARNA','MOTOMEL','MONDIAL','ZANELLA','GUERRERO','KELLER','CORVEN','HONDA','GILERA','YAMAHA','SUZUKI','BAJAJ','BENELLI','KYMCO','PIAGGIO','VESPA','TRIUMPH','DUCATI','APRILIA','KTM','BMW','HERO','SIAM','IKA','TVS','SYM','OKINOI','KEEWAY','VOGE','QJMOTOR','ZONTES','MORINI','INDIAN'];
function splitModel(s){const raw=String(s??'').replace(/\s+/g,' ').trim(),u=raw.toUpperCase();const b=brands.find(x=>u===x||u.startsWith(x+' '))||u.split(' ')[0]||'UNKNOWN';return {brand:b,model:raw.slice(b.length).trim()||raw,canonical_model_key:u};}
function isoDate(y,m,d){const dt=new Date(Date.UTC(y,m-1,d));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==m-1||dt.getUTCDate()!==d)return null;return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
const mon={ene:1,jan:1,feb:2,mar:3,abr:4,apr:4,may:5,jun:6,jul:7,ago:8,aug:8,sep:9,oct:10,nov:11,dic:12,dec:12};
function parseDate(v){if(v instanceof Date&&!isNaN(v))return isoDate(v.getFullYear(),v.getMonth()+1,v.getDate());const s=String(v??'').trim();let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;return isoDate(y,+m[2],+m[1])}m=norm(s).match(/^(\d{1,2}) ([a-z]{3,}) (\d{2,4})$/);if(m&&mon[m[2].slice(0,3)]){let y=+m[3];if(y<100)y+=2000;return isoDate(y,mon[m[2].slice(0,3)],+m[1])}const d=new Date(s);return !isNaN(d)&&d.getFullYear()>2000?isoDate(d.getFullYear(),d.getMonth()+1,d.getDate()):null}
function parsePeriod(v){const d=parseDate(v);if(d)return d.slice(0,7);let s=String(v??'').trim(),n=norm(s);let m=n.match(/^(\d{4})[ -](\d{1,2})$/);if(m&&+m[2]>=1&&+m[2]<=12)return `${m[1]}-${String(+m[2]).padStart(2,'0')}`;m=n.match(/^([a-z]{3,})[ -](\d{2,4})$/);if(m&&mon[m[1].slice(0,3)]){let y=+m[2];if(y<100)y+=2000;return `${y}-${String(mon[m[1].slice(0,3)]).padStart(2,'0')}`};m=n.match(/^(\d{1,2})[ -]([a-z]{3,})[ -](\d{2,4})$/);if(m&&mon[m[2].slice(0,3)]){let y=+m[3];if(y<100)y+=2000;return `${y}-${String(mon[m[2].slice(0,3)]).padStart(2,'0')}`};return null}
function sheetRows(wb,name){return XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:'',raw:false,blankrows:false})}
function headerScore(row,aliases){const ns=row.map(norm);return Object.values(aliases).reduce((a,arr)=>a+(arr.some(x=>ns.some(h=>h===x||h.includes(x)))?1:0),0)}
function findHeader(rows,aliases,min=2){let best={i:-1,s:-1};rows.slice(0,35).forEach((r,i)=>{const s=headerScore(r,aliases);if(s>best.s)best={i,s}});return best.s>=min?best.i:-1}
function colMap(row,aliases){const ns=row.map(norm),o={};for(const [k,arr] of Object.entries(aliases)){let i=ns.findIndex(h=>arr.some(a=>h===a||h.includes(a)));if(i>=0)o[k]=i}return o}
const A={brand:['marca','brand'],model:['modelo','model','descripcion','description'],units:['unidades','unidad','cantidad','quantity','qty','patentamientos','registrations','importaciones'],period:['periodo','period','mes','month','fecha','date'],origin:['pais origen','country origin','origen'],type:['tipo importacion','import type','regimen','tipo'],seg1:['segmento 1','segment 1','segmentation 1'],seg2:['segmento 2','segment 2','segmentation 2'],segm:['honda planning','segment management','segmento management'],segt:['honda pp2w','segment tool','segmento tool'],cc:['cilindrada','cc'],group:['grupo','group','group name'],active:['activo','active']};
function detectWorkbook(wb,forced='auto'){
 if(forced!=='auto')return forced;
 for(const name of wb.SheetNames){const rows=sheetRows(wb,name).slice(0,20);for(const r of rows){const n=r.map(norm);if(n.some(x=>x==='descripcion'||x==='description')&&r.filter(x=>parseDate(x)).length>=2)return 'daily'}}
 if(wb.SheetNames.some(n=>norm(n).includes('import')))return 'imports';
 for(const name of wb.SheetNames){const rows=sheetRows(wb,name);const hi=findHeader(rows,A,2);if(hi>=0){const h=rows[hi];if(h.filter(x=>parsePeriod(x)).length>=3)return 'monthly'}}
 return 'models';
}
function preferredSheet(wb,type){const names=wb.SheetNames;if(type==='imports')return names.find(n=>norm(n).includes('import'))||names[0];if(type==='monthly')return names.find(n=>/pivot|registration|patent|segmentation/i.test(n))||names[0];if(type==='models')return names.find(n=>/filtro|segment|model|master/i.test(n))||names[0];return names[0]}
function parseDaily(wb){let name=preferredSheet(wb,'daily'),rows=sheetRows(wb,name),hi=-1;for(let i=0;i<Math.min(30,rows.length);i++){const n=rows[i].map(norm);if(n.some(x=>x==='descripcion'||x==='description')&&rows[i].filter(x=>parseDate(x)).length>=2){hi=i;break}}if(hi<0)throw new Error('No encontré una cabecera Descripción + fechas en el Daily.');const h=rows[hi],dateCols=h.map((v,i)=>({i,date:parseDate(v)})).filter(x=>x.date),desc=h.findIndex(v=>['descripcion','description'].includes(norm(v)));const out=[],tot={};for(const r of rows.slice(hi+1)){const label=String(r[desc]??'').trim();if(!label||norm(label)==='total')continue;const sm=splitModel(label);for(const c of dateCols){const q=Math.round(num(r[c.i]));if(!q)continue;out.push({registration_date:c.date,period:c.date.slice(0,7),brand:sm.brand,model:sm.model,canonical_model_key:sm.canonical_model_key,province:null,quantity:q});tot[c.date]=(tot[c.date]||0)+q}}const dailyTotals=Object.entries(tot).sort().map(([market_date,market_total])=>({market_date,period:market_date.slice(0,7),market_total}));return {type:'daily',sheet:name,rows:out,dailyTotals,sourceDate:dailyTotals.at(-1)?.market_date||null,warnings:[]}}
function parseWideOrLong(wb,type){const name=preferredSheet(wb,type),rows=sheetRows(wb,name),hi=findHeader(rows,A,type==='imports'?1:2);if(hi<0)throw new Error('No pude identificar las columnas principales del archivo.');const h=rows[hi],m=colMap(h,A),periodCols=h.map((v,i)=>({i,period:parsePeriod(v)})).filter(x=>x.period&&iSafe(i=>true));function iSafe(){return true}const out=[],warnings=[];for(const r of rows.slice(hi+1)){const brand=m.brand!=null?String(r[m.brand]??'').trim():'';const model=m.model!=null?String(r[m.model]??'').trim():'';if(!brand&&!model)continue;const sm=brand?{brand:brand.toUpperCase(),model:model||brand,canonical_model_key:`${brand} ${model}`.toUpperCase().replace(/\s+/g,' ').trim()}:splitModel(model);const common={brand:sm.brand,model:sm.model,canonical_model_key:sm.canonical_model_key,segment_management:m.segm!=null?String(r[m.segm]??'').trim()||null:null,segment_tool:m.segt!=null?String(r[m.segt]??'').trim()||null:null,segment_1:m.seg1!=null?String(r[m.seg1]??'').trim()||null:null,segment_2:m.seg2!=null?String(r[m.seg2]??'').trim()||null:null,cc:m.cc!=null?Math.round(num(r[m.cc]))||null:null,group_name:m.group!=null?String(r[m.group]??'').trim()||null:null};if(m.period!=null&&m.units!=null){const p=parsePeriod(r[m.period]);const q=num(r[m.units]);if(p&&q)out.push(type==='imports'?{period:p,brand:sm.brand,model:sm.model,canonical_model_key:sm.canonical_model_key,units:q,import_type:m.type!=null?String(r[m.type]??'').trim()||null:null,country_origin:m.origin!=null?String(r[m.origin]??'').trim()||null:null}:{period:p,...common,quantity:Math.round(q)})}else if(periodCols.length){for(const c of periodCols){if(c.i===m.cc||c.i===m.seg1||c.i===m.seg2||c.i===m.group)continue;const q=num(r[c.i]);if(!q)continue;out.push(type==='imports'?{period:c.period,brand:sm.brand,model:sm.model,canonical_model_key:sm.canonical_model_key,units:q,import_type:m.type!=null?String(r[m.type]??'').trim()||null:null,country_origin:m.origin!=null?String(r[m.origin]??'').trim()||null:null}:{period:c.period,...common,quantity:Math.round(q)})}}}
 if(!out.length)warnings.push('No se encontraron valores distintos de cero con período identificable.');return {type,sheet:name,rows:out,dailyTotals:[],sourceDate:null,warnings}}
function parseModels(wb){const name=preferredSheet(wb,'models'),rows=sheetRows(wb,name),hi=findHeader(rows,A,2);if(hi<0)throw new Error('No encontré Marca/Modelo en el master.');const m=colMap(rows[hi],A),out=[];for(const r of rows.slice(hi+1)){const brand=m.brand!=null?String(r[m.brand]??'').trim():'';const model=m.model!=null?String(r[m.model]??'').trim():'';if(!brand&&!model)continue;const sm=brand?{brand:brand.toUpperCase(),model:model||brand,canonical_model_key:`${brand} ${model}`.toUpperCase().replace(/\s+/g,' ').trim()}:splitModel(model);out.push({canonical_key:sm.canonical_model_key,brand:sm.brand,model:sm.model,segment_management:m.segm!=null?String(r[m.segm]??'').trim()||null:null,segment_tool:m.segt!=null?String(r[m.segt]??'').trim()||null:null,segment_1:m.seg1!=null?String(r[m.seg1]??'').trim()||null:null,segment_2:m.seg2!=null?String(r[m.seg2]??'').trim()||null:null,cc:m.cc!=null?Math.round(num(r[m.cc]))||null:null,group_name:m.group!=null?String(r[m.group]??'').trim()||null:null,active:m.active!=null?!['no','false','0','inactivo'].includes(norm(r[m.active])):true,metadata:{source_sheet:name}})}return {type:'models',sheet:name,rows:out,dailyTotals:[],sourceDate:null,warnings:[]}}
async function hashBuffer(buf){const h=await crypto.subtle.digest('SHA-256',buf);return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function parseFile(file,forced){if(!window.XLSX)throw new Error('No cargó el lector Excel. Recargá la página.');const buf=await file.arrayBuffer(),checksum=await hashBuffer(buf),wb=XLSX.read(buf,{type:'array',cellDates:true});const type=detectWorkbook(wb,forced);let result;if(type==='daily')result=parseDaily(wb);else if(type==='imports')result=parseWideOrLong(wb,'imports');else if(type==='monthly')result=parseWideOrLong(wb,'monthly');else result=parseModels(wb);return {...result,checksum,fileName:file.name,fileSize:file.size,sheets:wb.SheetNames}}
function api(path='',opts={}){const key=$('#dataHubKey')?.value?.trim()||localStorage.getItem(STORE_KEY)||'';return fetch(ENDPOINT+path,{...opts,headers:{'content-type':'application/json','x-upload-key':key,...(opts.headers||{})}}).then(async r=>{const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(r.status===401?'Clave de carga incorrecta.':j.detail||j.error||`HTTP ${r.status}`);return j})}
function typeLabel(t){return ({daily:'Daily Registration · SIOMAA',imports:'Importaciones',monthly:'Histórico / Pivot mensual',models:'Master de modelos y segmentos'})[t]||t}
function formatDate(s){if(!s)return '—';try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:s.includes('T')?'short':undefined}).format(new Date(s.includes('T')?s:s+'T12:00:00'))}catch{return s}}
function setMsg(text,t='info'){const e=$('#dataHubMessage');if(!e)return;e.className=`data-hub-message show ${t}`;e.textContent=text}
function setProgress(p,text){const e=$('#dataHubProgress'),bar=$('#dataHubProgress i'),lab=$('#dataHubProgress small');if(!e)return;e.classList.toggle('show',p>=0);if(bar)bar.style.width=`${Math.max(0,Math.min(100,p))}%`;if(lab)lab.textContent=text||''}
function renderPreview(){const box=$('#dataHubPreview'),meta=$('#dataHubDetected'),confirm=$('#dataHubConfirm');if(!box)return;if(!parsed){box.innerHTML='<div class="data-preview-empty">Elegí un archivo para ver la vista previa antes de actualizar la base.</div>';if(meta)meta.innerHTML='Sin archivo analizado';if(confirm)confirm.disabled=true;return}const rows=parsed.rows.slice(0,12),keys=[...new Set(rows.flatMap(Object.keys))].filter(k=>!['metadata'].includes(k)).slice(0,9);box.innerHTML=rows.length?`<table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="data-preview-empty">No se detectaron filas cargables.</div>';const periods=parsed.rows.map(r=>r.period).filter(Boolean).sort();meta.innerHTML=`<span class="data-pill">${esc(typeLabel(parsed.type))}</span><div class="data-status-row"><span>Archivo</span><b>${esc(parsed.fileName)}</b></div><div class="data-status-row"><span>Hoja usada</span><b>${esc(parsed.sheet)}</b></div><div class="data-status-row"><span>Registros a cargar</span><b>${parsed.rows.length.toLocaleString('es-AR')}</b></div><div class="data-status-row"><span>Período</span><b>${esc(periods.length?`${periods[0]} → ${periods.at(-1)}`:'—')}</b></div><div class="data-status-row"><span>Checksum</span><b>${esc(parsed.checksum.slice(0,12))}…</b></div>${parsed.warnings.map(w=>`<div class="data-status-row"><span>Alerta</span><b>${esc(w)}</b></div>`).join('')}`;if(confirm)confirm.disabled=!parsed.rows.length||busy}
function summaryTile(title,value,sub=''){return `<div class="data-summary-tile"><span>${title}</span><b>${esc(value||'—')}</b><small>${esc(sub)}</small></div>`}
function renderStatus(j){lastStatus=j;const runs=Array.isArray(j?.runs)?j.runs:[],latest={};for(const r of runs)if(!latest[r.dataset]&&r.status==='success')latest[r.dataset]=r;const daily=j?.daily||[],latestDay=daily[0];const currentPeriod=latestDay?.period,monthTotal=daily.filter(x=>x.period===currentPeriod).reduce((a,b)=>a+Number(b.market_total||0),0);const s=$('#dataHubSummary');if(s)s.innerHTML=summaryTile('DAILY / SIOMAA',latest.daily?.source_date||latestDay?.market_date,latest.daily?.source_file_name||'Sin carga')+summaryTile('MTD CARGADO',monthTotal?monthTotal.toLocaleString('es-AR'):'—',currentPeriod||'Daily')+summaryTile('IMPORTACIONES',latest.imports?.source_date||latest.imports?.finished_at?.slice(0,10),latest.imports?.source_file_name||'Sin carga')+summaryTile('PIVOT / MASTER',latest.monthly?.source_date||latest.models?.source_date||latest.monthly?.finished_at?.slice(0,10)||latest.models?.finished_at?.slice(0,10),latest.monthly?.source_file_name||latest.models?.source_file_name||'Sin carga');const h=$('#dataHubHistory');if(h)h.innerHTML=runs.length?`<table><thead><tr><th>Fecha</th><th>Base</th><th>Archivo</th><th>Filas</th><th>Estado</th></tr></thead><tbody>${runs.slice(0,15).map(r=>`<tr><td>${esc(formatDate(r.finished_at||r.started_at))}</td><td>${esc(typeLabel(r.dataset))}</td><td>${esc(r.source_file_name||'—')}</td><td>${Number(r.records_loaded||0).toLocaleString('es-AR')}</td><td class="${esc(r.status)}">${esc(r.status)}</td></tr>`).join('')}</tbody></table>`:'<div class="data-preview-empty">Todavía no hay cargas registradas.</div>';decorateBand(latest,latestDay)}
function decorateBand(latest,latestDay){$$('.update-band>div').forEach(d=>{const label=norm(d.querySelector('span')?.textContent);const b=d.querySelector('b');if(!b)return;if(label==='siomaa'&&(latest.daily||latestDay))b.textContent=latest.daily?.source_date||latestDay?.market_date||'OK';if(label==='imports'&&latest.imports)b.textContent=latest.imports.source_date||latest.imports.finished_at?.slice(0,10)||'OK'})}
async function loadStatus(silent=false){const key=$('#dataHubKey')?.value?.trim()||localStorage.getItem(STORE_KEY);if(!key){if(!silent)setMsg('Pegá la clave de carga una sola vez. Queda guardada únicamente en este navegador.','info');return}try{const j=await api('?action=status');renderStatus(j);if(!silent)setMsg('Base conectada. Podés cargar un archivo.','ok')}catch(e){if(!silent)setMsg(e.message,'error')}}
async function onFile(file){if(!file||busy)return;const ext=file.name.split('.').pop().toLowerCase();if(!['xls','xlsx','csv'].includes(ext)){setMsg('Formato no admitido. Usá XLS, XLSX o CSV.','error');return}try{busy=true;setMsg('Leyendo y normalizando el archivo…','info');setProgress(8,'Analizando hojas y columnas');const forced=$('#dataHubType')?.value||'auto';parsed=await parseFile(file,forced);fileMeta=file;setProgress(-1,'');renderPreview();setMsg(`Detecté ${typeLabel(parsed.type)} con ${parsed.rows.length.toLocaleString('es-AR')} registros listos para revisar.`,'ok')}catch(e){parsed=null;renderPreview();setMsg(e.message,'error')}finally{busy=false;renderPreview()}}
async function confirmUpload(){if(!parsed||busy)return;const key=$('#dataHubKey')?.value?.trim();if(!key){setMsg('Ingresá la clave de carga antes de confirmar.','error');return}localStorage.setItem(STORE_KEY,key);let runId=null;try{busy=true;renderPreview();setProgress(2,'Abriendo carga gobernada');const start=await api('',{method:'POST',body:JSON.stringify({action:'start',dataset:parsed.type,fileName:parsed.fileName,checksum:parsed.checksum,sourceDate:parsed.sourceDate})});if(start.duplicate){setProgress(-1,'');setMsg('Ese mismo archivo ya fue cargado correctamente. No se volvió a duplicar en la base.','info');await loadStatus(true);return}runId=start.run.id;let loaded=0;for(let i=0;i<parsed.rows.length;i+=CHUNK){const rows=parsed.rows.slice(i,i+CHUNK);const r=await api('',{method:'POST',body:JSON.stringify({action:'chunk',dataset:parsed.type,runId,fileName:parsed.fileName,rows})});loaded+=Number(r.loaded||0);const p=5+Math.round((Math.min(i+CHUNK,parsed.rows.length)/parsed.rows.length)*88);setProgress(p,`Cargando ${loaded.toLocaleString('es-AR')} / ${parsed.rows.length.toLocaleString('es-AR')} registros`)}await api('',{method:'POST',body:JSON.stringify({action:'finish',runId,recordsLoaded:loaded,dailyTotals:parsed.dailyTotals||[],notes:`Hoja: ${parsed.sheet}`})});setProgress(100,'Carga finalizada y base actualizada');setMsg(`Carga confirmada: ${loaded.toLocaleString('es-AR')} registros incorporados a ${typeLabel(parsed.type)}.`,'ok');await loadStatus(true);setTimeout(()=>setProgress(-1,''),1600)}catch(e){if(runId){try{await api('',{method:'POST',body:JSON.stringify({action:'abort',runId,notes:e.message})})}catch{}}setProgress(-1,'');setMsg(`No se actualizó la base: ${e.message}`,'error')}finally{busy=false;renderPreview()}}
function hubHtml(){const saved=localStorage.getItem(STORE_KEY)||'';return `<section id="datahub" class="single-chapter data-hub-chapter"><header><i>11</i><div><span>CAPÍTULO 11</span><h2>Data Hub · Actualizar la base</h2><p>Cargá directamente los Excel de Daily Registration, Importaciones, Pivot histórico o Master de modelos. La app valida y muestra una vista previa antes de escribir en la base.</p></div></header><div class="data-hub-shell"><div class="data-hub-summary" id="dataHubSummary">${summaryTile('DAILY / SIOMAA','—','Sin consultar')}${summaryTile('MTD CARGADO','—','Daily')}${summaryTile('IMPORTACIONES','—','Sin consultar')}${summaryTile('PIVOT / MASTER','—','Sin consultar')}</div><div class="data-hub-grid"><div class="data-hub-card"><h3>Cargar archivo</h3><p>No hace falta modificar el Excel antes. El importador reconoce los formatos que venís usando y normaliza la información.</p><div class="data-hub-fields"><label class="data-hub-field"><span>TIPO DE BASE</span><select id="dataHubType"><option value="auto">Detectar automáticamente</option><option value="daily">Daily Registration / SIOMAA</option><option value="imports">Importaciones</option><option value="monthly">Pivot / Histórico mensual</option><option value="models">Master modelos / segmentos</option></select></label><label class="data-hub-field"><span>CLAVE DE CARGA</span><input id="dataHubKey" type="password" autocomplete="off" placeholder="Clave de actualización" value="${esc(saved)}"></label></div><label class="data-drop" id="dataHubDrop"><input id="dataHubFile" type="file" accept=".xls,.xlsx,.csv"><div><strong>Arrastrá el Excel acá o tocá para elegirlo</strong><small>XLS · XLSX · CSV<br>Primero se analiza; nada impacta hasta tocar “Confirmar actualización”.</small></div></label><div class="data-hub-progress" id="dataHubProgress"><div class="data-hub-progress-track"><i></i></div><small></small></div><div class="data-hub-actions"><button class="primary" id="dataHubConfirm" disabled>Confirmar actualización</button><button class="secondary" id="dataHubRefresh">Ver estado de la base</button></div><div class="data-hub-message" id="dataHubMessage"></div></div><div class="data-hub-card"><h3>Archivo detectado</h3><p id="dataHubDetected">Sin archivo analizado</p><div class="data-preview" id="dataHubPreview"><div class="data-preview-empty">Elegí un archivo para ver la vista previa antes de actualizar la base.</div></div></div></div><div class="data-hub-card"><h3>Historial de cargas</h3><p>Queda trazabilidad del archivo, fecha, base afectada, filas cargadas y estado. Un checksum evita duplicar exactamente el mismo archivo.</p><div class="data-history" id="dataHubHistory"><div class="data-preview-empty">Ingresá la clave para consultar el historial.</div></div></div></div></section>`}
function bindHub(){const root=$('#datahub');if(!root||root.dataset.bound)return;root.dataset.bound='1';const f=$('#dataHubFile'),drop=$('#dataHubDrop'),key=$('#dataHubKey');f?.addEventListener('change',e=>onFile(e.target.files?.[0]));drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop?.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');onFile(e.dataTransfer.files?.[0])});key?.addEventListener('change',()=>{if(key.value.trim())localStorage.setItem(STORE_KEY,key.value.trim());loadStatus()});$('#dataHubRefresh')?.addEventListener('click',()=>loadStatus());$('#dataHubConfirm')?.addEventListener('click',confirmUpload);$('#dataHubType')?.addEventListener('change',()=>{if(fileMeta)onFile(fileMeta)});loadStatus(true)}
function navHub(){const n=$('#navigation');if(n&&!n.querySelector('[data-anchor="datahub"]'))n.insertAdjacentHTML('beforeend','<button data-anchor="datahub"><i>11</i><span>Data Hub · Cargar Excel</span></button>');const b=n?.querySelector('[data-anchor="datahub"]');if(b&&!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',()=>{$('#datahub')?.scrollIntoView({behavior:'smooth',block:'start'});$('#sidebar')?.classList.remove('open')})}}
function observeHub(){if(io)io.disconnect();if(!('IntersectionObserver'in window))return;const sec=$('#datahub');if(!sec)return;io=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting))$$('#navigation [data-anchor]').forEach(b=>b.classList.toggle('active',b.dataset.anchor==='datahub'))},{rootMargin:'-20% 0px -65% 0px'});io.observe(sec)}
function ensureHub(){const c=$('#content');if(!c||!window.DATA)return;if(!$('#datahub')){c.insertAdjacentHTML('beforeend',hubHtml());bindHub();observeHub()}navHub();if(lastStatus){const runs=lastStatus.runs||[],latest={};for(const r of runs)if(!latest[r.dataset]&&r.status==='success')latest[r.dataset]=r;decorateBand(latest,lastStatus.daily?.[0])}}
function start(){ensureHub();const c=$('#content');if(c)new MutationObserver(()=>queueMicrotask(ensureHub)).observe(c,{childList:true});const n=$('#navigation');if(n)new MutationObserver(()=>queueMicrotask(navHub)).observe(n,{childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,0));else setTimeout(start,0);
})();