/* Master architecture v2 — 33-sheet governed analysis */
const MASTER_SHEETS=[
  ['argentina','01','Argentina hoy'],['overview','02','Resumen ejecutivo'],['affordability','03','Consumidor y affordability'],['automoto','04','Autos versus motos'],['market','05','Mercado actual y nowcast'],['momentum','06','Momentum y cambio de régimen'],['history','07','Historia'],['seasonality','08','Estacionalidad'],['segments','09','Segmentos'],['competition','10','Marcas, grupos y modelos'],['imports','11','Importaciones y supply'],['product','12','Producto y competencia'],['newmodels','13','Nuevos modelos y amenazas'],['intelligence','14','Radar de noticias'],['diagnostic','15','Diagnóstico del mercado'],['scenarios','16','Tres escenarios'],['probability','17','Probabilidad y posibilidad'],['userlab','18','User Scenario Lab'],['forecast','19','Forecast mensual'],['forecastcy','20','Forecast CY'],['forecastki','21','Forecast KI actual'],['futureki','22','Próximos cinco KI'],['kicompare','23','Comparador KI y escenarios'],['method','24','Metodología del forecast'],['validation','25','Validación y backtesting'],['honda','26','Commercial Planning'],['productplanning','27','Product Planning'],['geography','28','Geografía'],['safety','29','Safety y regulación'],['actions','30','Riesgos y acciones'],['reports','31','Reportes'],['data','32','Data y metodología'],['updates','33','Centro de actualización']
];
Object.assign(TITLES,Object.fromEntries(MASTER_SHEETS.map(([k,,t])=>[k,t])));
const MASTER={
  probs:JSON.parse(localStorage.getItem('ami.master.probs')||'{"down":20,"base":60,"up":20}'),
  weights:JSON.parse(localStorage.getItem('ami.master.weights')||'{"market":25,"macro":20,"affordability":20,"seasonality":10,"supply":10,"product":10,"policy":5}'),
  userLikelihood:Number(localStorage.getItem('ami.userLikelihood')||50)
};
function mStatus(text='PENDING',toneName='amber'){return badge(text,toneName)}
function masterSave(){localStorage.setItem('ami.master.probs',JSON.stringify(MASTER.probs));localStorage.setItem('ami.master.weights',JSON.stringify(MASTER.weights));localStorage.setItem('ami.userLikelihood',String(MASTER.userLikelihood))}
function coreProbTotal(){return ['down','base','up'].reduce((a,k)=>a+(Number(MASTER.probs[k])||0),0)}
function coreExpected(row){const t=coreProbTotal()||100;return Math.round(((row.down||0)*MASTER.probs.down+(row.base||0)*MASTER.probs.base+(row.up||0)*MASTER.probs.up)/t)}
function normalizeProbabilities(){const t=coreProbTotal();if(!t){MASTER.probs={down:20,base:60,up:20};return}Object.keys(MASTER.probs).forEach(k=>MASTER.probs[k]=Math.round(MASTER.probs[k]/t*100));const d=100-coreProbTotal();MASTER.probs.base+=d;masterSave()}
normalizeProbabilities();

/* Probability rule override: User is separate unless explicitly made mutually exclusive. */
probTotal=function(){return coreProbTotal()};
scenarioExpected=function(row){return coreExpected(row)};
syncUserScenario=function(){
  if(!DATA)return; const factor=1+STORY.userAdj/100;
  DATA.forecast.rows.forEach(r=>{r.user=Math.round(r.base*factor);r.expected=coreExpected(r)});
  (DATA.forecast.segments||[]).forEach((r,i)=>{
    const total=DATA.forecast.rows[i]?.user||r.total.base;
    const alloc=applyLargestRemainder(r.segments,total);
    r.total.user=total;r.total.expected=DATA.forecast.rows[i]?.expected||coreExpected(r.total);
    r.segments.forEach(s=>{s.user=alloc[s.name];s.expected=coreExpected(s)});
  });
  (DATA.honda?.forecast||[]).forEach(r=>{r.user=Math.round(r.base*factor);r.expected=coreExpected(r)});
};
probabilityEditor=function(){
  const p=MASTER.probs,total=coreProbTotal();
  return `<div class="prob-editor"><div class="user-view"><div><span>VISIÓN USUARIO</span><b>${STORY.userAdj>=0?'+':''}${STORY.userAdj.toFixed(1)}% vs Base</b><small>No integra el 100% de Down/Base/Up</small></div><input id="userAdj" type="range" min="-20" max="20" step="0.5" value="${STORY.userAdj}"></div><div class="prob-grid">${['down','base','up'].map(k=>`<label><span>${k[0].toUpperCase()+k.slice(1)}</span><input class="master-prob" data-prob="${k}" type="number" min="0" max="100" step="5" value="${p[k]}"><small>%</small></label>`).join('')}<label><span>User likelihood</span><input id="userLikelihood" type="number" min="0" max="100" step="5" value="${MASTER.userLikelihood}"><small>% compat.</small></label></div><div class="prob-total ${total===100?'ok':'bad'}"><span>Down + Base + Up</span><b>${total}%</b><small>${total===100?'Distribución válida':'Debe sumar 100%'}</small></div></div>`;
};

function masterNav(){return MASTER_SHEETS.map(([view,n,title])=>`<button data-view="${view}" class="${state.view===view?'active':''}"><i>${n}</i><span>${title}</span></button>`).join('')}
function installMasterNav(){const nav=$('#navigation');if(!nav)return;nav.innerHTML=masterNav();$$('#navigation button').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;masterRender()}));const brand=$('.brand');if(brand)brand.href='#argentina'}
function sheetStatus(name,status,detail,toneName='green'){return `<div class="source"><div><b>${name}</b><small>${detail}</small></div>${mStatus(status,toneName)}</div>`}
function pendingCard(title,need){return card(title,'Fuente o cálculo todavía no conectado.',`<div class="pending-block">${mStatus('PENDING','amber')}<p>${need}</p><small>No se completa con estimaciones silenciosas.</small></div>`,'DATA CONTRACT')}
function factCard(title,value,note){return kpi(title,value,note,COLORS.green,'FACT')}
function statusFromMacro(regex){return (DATA.macro||[]).find(x=>regex.test(norm(x.metric)))||null}
function sumRows(rows,key='value'){return rows.reduce((a,b)=>a+(Number(b[key])||0),0)}
function rollingSeries(windowSize){const src=DATA.market_history||[];return src.map((r,i)=>{if(i<windowSize-1)return null;const s=src.slice(i-windowSize+1,i+1);return {period:r.period,value:sumRows(s)/windowSize}}).filter(Boolean)}
function lastHistory(){return DATA.market_history?.at(-1)}
function sourceDateFor(re){const m=(DATA.macro||[]).find(x=>re.test(norm(x.metric)));return m?`${m.date} · ${m.metric}`:'Sin corte conectado'}
function scenarioRows(){return (DATA.forecast?.rows||[]).map(r=>({...r,user:r.user??Math.round(r.base*(1+STORY.userAdj/100)),expected:r.expected??coreExpected(r)}))}
function currentKI2(){return typeof currentKI==='function'?currentKI():{label:'KI 26/27',down:0,base:0,up:0,user:0,expected:0}}

function renderUpdates(){
 const cutoff=DATA.meta?.market_cutoff||'—',imp=DATA.meta?.imports_cutoff||DATA.imports?.cutoff||'—',priceDate=DATA.product_planning?.prices?.[0]?.valid_through||'—';
 const items=[
  ['CAFAM','FACT',`Mercado total · ${cutoff}`,'green'],['Pivot Table','FACT',`${DATA.market_history?.[0]?.period||'2010-01'} → ${cutoff} · historia/estacionalidad`,'green'],['AUTOMATIC / Segmentation','FACT',`Estructura · ${DATA.meta?.structure_cutoff||DATA.meta?.segment_cutoff||'último corte'}`,'green'],['SIOMAA','PENDING','Sin archivo diario vigente conectado en esta build','amber'],['INDEC',(DATA.macro||[]).length?'FACT':'PENDING',sourceDateFor(/IPC|SALARIO|EMAE|ACTIVIDAD/),(DATA.macro||[]).length?'green':'amber'],['BCRA',(DATA.macro||[]).length?'FACT':'PENDING',sourceDateFor(/TASA|BADLAR|TAMAR|CREDITO/),(DATA.macro||[]).length?'green':'amber'],['Importaciones',imp!=='—'?'FACT':'PENDING',`Último archivo: ${imp}`,imp!=='—'?'green':'amber'],['Precios',priceDate!=='—'?'FACT':'PENDING',`Última vigencia: ${priceDate}`,priceDate!=='—'?'green':'amber'],['Honda interno','USER INPUT','No publicar como FACT en versión abierta','amber']
 ];
 return head('UPDATE CENTER','Centro de actualización','Antes de interpretar el mercado, esta hoja muestra qué está fresco, qué falta y qué cambió. Diferencias visibles, sin alarmismo.')+
 `<section class="kpis">${factCard('MES CERRADO',cutoff,'CAFAM gobierna')}${kpi('FORECAST',DATA.forecast?.version||'—','versión vigente',COLORS.blue,'FORECAST')}${kpi('GAP FUENTES',fmt(DATA.executive?.source_gap||0),'Pivot − CAFAM',COLORS.amber,'FACT')}${kpi('SIOMAA','PENDING','mes abierto / daily',COLORS.amber,'PENDING')}${kpi('CALIDAD','COBERTURA PARCIAL','sin datos inventados',COLORS.green,'CONTROLLED')}</section>`+
 card('Cobertura de fuentes','Fecha, estado y rol de cada fuente.',`<div class="source-list">${items.map(x=>sheetStatus(...x)).join('')}</div>`,'DATA FRESHNESS')+
 card('Cambios desde la versión anterior','Toda modificación de forecast debe ser versionada.',`<div class="changelog-box"><b>${DATA.forecast?.version||'Forecast vigente'}</b><p>${DATA.forecast?.method||'Metodología base sin cambio silencioso.'}</p><small>${DATA.meta?.generated_at||DATA.meta?.enriched_at||'Fecha de build no informada'}</small></div>`,'CHANGELOG');
}
function renderAffordabilityMaster(){
 const prices=DATA.product_planning?.prices||[]; const wage=statusFromMacro(/SALARIO/),credit=statusFromMacro(/CREDITO|TASA/),infl=statusFromMacro(/IPC|INFLACION/);
 return head('CONSUMER','Consumidor y affordability','¿La gente realmente puede comprar una moto? Se separa precio, ingreso, cuota y costo de uso; si falta CFT o salario compatible, queda pendiente.')+
 `<section class="kpis">${kpi('SALARIO / INGRESO',wage?.value||'PENDING',wage?.date||'mismo corte requerido',wage?COLORS.green:COLORS.amber,wage?'FACT':'PENDING')}${kpi('CRÉDITO',credit?.value||'PENDING',credit?.date||'tasa efectiva / CFT',COLORS.amber,credit?'FACT':'PENDING')}${kpi('INFLACIÓN',infl?.value||'PENDING',infl?.date||'último IPC',COLORS.amber,infl?'FACT':'PENDING')}${kpi('PRECIOS',prices.length,`modelos con snapshot`,COLORS.blue,prices.length?'FACT':'PENDING')}</section>`+
 `<div class="grid two">${card('Precios observados','Snapshots oficiales o declarados con vigencia.',`<div class="table-wrap"><table class="table"><thead><tr><th>Modelo</th><th>Precio</th><th>Vigencia</th><th>Estado</th></tr></thead><tbody>${prices.slice(0,15).map(p=>`<tr><td><strong>${p.model}</strong></td><td>${p.price?money(p.price):`${money(p.price_from)} – ${money(p.price_to)}`}</td><td>${p.valid_through||'—'}</td><td>${mStatus('FACT','green')}</td></tr>`).join('')}</tbody></table></div>`,'PRICE')}${pendingCard('Cuota / salario / CFT','Requiere tasa efectiva, anticipo, plazo y salario del mismo corte por modelo/segmento.')}</div>`+
 card('Índice de affordability','Framework de cálculo y sensibilidad.',`<div class="decision-grid"><div><b>01</b><h3>Ingreso real</h3><p>Salario nominal deflactado y empleo estable.</p></div><div><b>02</b><h3>Precio + financiación</h3><p>Precio, anticipo, tasa, CFT y plazo.</p></div><div><b>03</b><h3>Costo de uso</h3><p>Combustible, seguro y mantenimiento.</p></div></div><div class="callout amber"><b>Estado:</b> ${mStatus('PENDING','amber')} El índice no se publica hasta alinear cortes y financiación efectiva.</div>`,'METHOD');
}
function renderAutoMoto(){return head('MOBILITY','Autos versus motos','La sustitución auto→moto sólo se calcula cuando ambos mercados y costos están alineados por mes y fuente.')+`<div class="grid two">${pendingCard('Patentamientos de autos','Conectar fuente gobernante de autos por mes, YTD, precios y financiación.')}${card('Mercado de motos','Serie gobernada CAFAM.',lineChart(periodRows(DATA.market_history).map(r=>({...r,moto:r.value})),[{key:'moto',name:'Motos',color:COLORS.red}],{zero:true}),'FACT')}</div>`+pendingCard('Índice de sustitución','Requiere auto/moto del mismo mes, precio de acceso, cuota y costo mensual de uso.')}
function renderMomentum(){const r3=rollingSeries(3),r6=rollingSeries(6),r12=rollingSeries(12),last=lastHistory(),regime=(last?.yoy||0)>.1?'EXPANSIVO':(last?.yoy||0)<-.05?'CONTRACTIVO':'NEUTRAL';return head('MOMENTUM','Momentum y cambio de régimen','Separa nivel de mercado de velocidad, persistencia y amplitud del crecimiento.',{tone:regime==='EXPANSIVO'?'green':regime==='CONTRACTIVO'?'red':'amber',text:regime})+`<section class="kpis">${kpi('ROLLING 3M',fmt(r3.at(-1)?.value),'promedio mensual',COLORS.red,'FACT')}${kpi('ROLLING 6M',fmt(r6.at(-1)?.value),'promedio mensual',COLORS.blue,'FACT')}${kpi('ROLLING 12M',fmt(r12.at(-1)?.value),'promedio mensual',COLORS.green,'FACT')}${kpi('YOY',pct(last?.yoy),'último cierre',COLORS.amber,'FACT')}</section>`+card('Rolling 3M / 6M / 12M','Persistencia del crecimiento en una misma escala.',lineChart(r12.map(r=>{const a=r3.find(x=>x.period===r.period),b=r6.find(x=>x.period===r.period);return {period:r.period,r3:a?.value,r6:b?.value,r12:r.value}}),[{key:'r3',name:'3M',color:COLORS.red},{key:'r6',name:'6M',color:COLORS.blue},{key:'r12',name:'12M',color:COLORS.green}],{zero:true}),'REGIME')+pendingCard('Difusión y break estructural','Requiere histórico comparable de marcas/modelos por mes y reglas de detección calibradas.')}
function renderHistory(){return head('HISTORY','Evolución histórica','Historia mensual desde 2010; vista recomendada desde 2013. Los hitos explicativos se anotan sólo con evidencia fechada.')+card('Mercado mensual 2010 → hoy','CAFAM gobierna cierres vigentes; Pivot extiende historia.',lineChart(periodRows(DATA.market_history).map(r=>({...r,market:r.value})),[{key:'market',name:'Mercado',color:COLORS.actual}],{zero:true}),'HISTÓRICO')+`<div class="grid two">${pendingCard('UIO / replacement / expansión','Requiere serie de parque y cohortes conectada al motor.')}${pendingCard('Hitos regulatorios y presidenciales','Se mostrarán como anotaciones fechadas, no como causalidad automática.')}</div>`}
function renderSeasonalityMaster(){const total=DATA.seasonality?.market?.monthly_index||[],months=(DATA.seasonality?.month_labels||MONTHS).map((m,i)=>({period:`2026-${String(i+1).padStart(2,'0')}`,median:total[i]}));const segs=Object.entries(DATA.seasonality?.management||{}).map(([name,obj])=>({name,sum:(obj.monthly_index||[]).reduce((a,b)=>a+b,0)}));return head('SEASONALITY','Estacionalidad','Perfiles robustos por mediana 2010–2025. 2026 valida pace, no entra como año completo.')+`<section class="kpis">${kpi('MERCADO Σ',total.reduce((a,b)=>a+b,0).toFixed(3),'debe ser 12,000',COLORS.green,'CONTROL')}${kpi('MÉTODO','MEDIANA','2010–2025',COLORS.blue,'FACT')}${kpi('2026','VALIDACIÓN','no año completo',COLORS.amber,'RULE')}</section>`+card('Mercado total','Índice mensual normalizado.',lineChart(months,[{key:'median',name:'Mediana',color:COLORS.blue}],{zero:false,minValue:.55,maxValue:1.45}),'TOTAL')+card('Controles por segmento','Cada perfil debe reconciliar Σ=12.',`<div class="table-wrap"><table class="table"><thead><tr><th>Segmento</th><th>Σ índices</th><th>Control</th></tr></thead><tbody>${segs.map(s=>`<tr><td>${s.name}</td><td>${s.sum.toFixed(3)}</td><td>${mStatus(Math.abs(s.sum-12)<.01?'OK':'REVISAR',Math.abs(s.sum-12)<.01?'green':'red')}</td></tr>`).join('')}</tbody></table></div>`,'QA')+pendingCard('MAD / dispersión / días hábiles','Requiere exponer distribución anual por mes y calendario hábil dentro del dataset publicado.')}
function renderNewModels(){const signals=DATA.imports?.new_model_signals||[];return head('THREATS','Nuevos modelos, rumores y amenazas','Una señal no se convierte automáticamente en Base. Se separa rumor, señal, confirmado y descartado.')+card('Detecciones por importaciones','Modelos sin presencia suficiente en ranking actual.',`<div class="signal-list">${signals.length?signals.map(x=>`<div class="intel-row"><div>${mStatus('EARLY SIGNAL','amber')}<b>${x.name}</b><small>${x.signal||'Importación detectada'}</small></div><strong>${fmt(x.units||0)}</strong></div>`).join(''):'<div class="empty">Sin señales cargadas.</div>'}</div>`,'IMPORT SIGNALS')+pendingCard('Homologaciones / rumores / lanzamientos','Conectar fuentes oficiales, medios, Instagram y homologaciones con nivel de confianza y probabilidad de llegada.')}
function renderDiagnostic(){const last=lastHistory(),top=DATA.segment_history?.at(-1)?.segments?.slice().sort((a,b)=>b.value-a.value)[0],risk=(DATA.macro||[]).filter(x=>tone(x.direction)!=='green').length;return head('DIAGNOSIS','Diagnóstico del mercado','Síntesis posterior a contexto + datos: crecimiento, sostenibilidad, drivers y qué monitorear.')+`<div class="diagnosis-grid"><div>${mStatus((last?.yoy||0)>0?'CRECE':'DECRECE',(last?.yoy||0)>0?'green':'red')}<h3>Mercado</h3><p>Último YoY ${pct(last?.yoy)} y MoM ${pct(last?.mom)}.</p></div><div>${mStatus(risk>2?'FRÁGIL':'FAVORABLE CON ALERTAS',risk>2?'amber':'green')}<h3>Sostenibilidad</h3><p>${risk} señales macro requieren seguimiento.</p></div><div>${mStatus('DRIVER','green')}<h3>Segmento</h3><p>${top?.name||'—'} lidera el último corte estructural.</p></div></div>`+card('Qué cambió / qué monitorear','Conclusión automática con trazabilidad.',`<div class="action-list"><div><b>1</b><span>Confirmar si el ritmo del mes abierto sostiene el régimen observado.</span></div><div><b>2</b><span>Vigilar affordability y tasa efectiva antes de subir Base.</span></div><div><b>3</b><span>Contrastar import pressure y lanzamientos contra patentamientos reales.</span></div></div>`,'NEXT')}
function renderScenarios(){const rows=scenarioRows();return head('SCENARIOS','Downside · Base · Upside · User','Los tres escenarios oficiales se muestran simultáneamente. User permanece separado del forecast oficial.')+probabilityEditor()+card('Curvas mensuales','User no modifica Base.',lineChart(rows,[{key:'down',name:'Down',color:COLORS.down},{key:'base',name:'Base',color:COLORS.red},{key:'up',name:'Up',color:COLORS.blue},{key:'user',name:'User',color:'#7c3aed'}],{zero:true}),'4 VIEWS')+`<div class="grid three">${card('Downside','Prevención',`<p>Supone deterioro de conversión, crédito o actividad. Probabilidad actual: <b>${MASTER.probs.down}%</b>.</p>`,'FORECAST')}${card('Base','Camino central',`<p>Convergencia + estacionalidad + momentum. Probabilidad actual: <b>${MASTER.probs.base}%</b>.</p>`,'FORECAST')}${card('Upside','Captura',`<p>Mejor affordability/actividad o demanda superior. Probabilidad actual: <b>${MASTER.probs.up}%</b>.</p>`,'FORECAST')}</div>`}
function renderProbability(){const wt=MASTER.weights;return head('PROBABILITY','Probabilidad y posibilidad','La precisión estadística no se inventa: hasta integrar backtesting completo, la distribución se etiqueta como ASSUMPTION y las ponderaciones quedan visibles/editables.')+probabilityEditor()+card('Ponderaciones del modelo de probabilidad','Ponderación inicial sugerida; todavía requiere calibración histórica.',`<div class="weight-grid">${Object.entries({market:'Mercado y momentum',macro:'Macro y consumidor',affordability:'Affordability y crédito',seasonality:'Estacionalidad',supply:'Supply / importaciones',product:'Producto / competencia',policy:'Política / regulación'}).map(([k,l])=>`<label><span>${l}</span><input class="weight-input" data-weight="${k}" type="number" min="0" max="100" value="${wt[k]}"><small>%</small></label>`).join('')}</div><div class="callout amber">${mStatus('ASSUMPTION','amber')} Hasta integrar MAPE/MAE/RMSE y cobertura histórica, estas probabilidades no se presentan como calibradas.</div>`,'CALIBRATION')+pendingCard('Posibilidad operativa','Producción, stock, red, compradores y supply cap deben conectarse antes de clasificar “operativamente imposible”.')}
function renderUserLab(){const cur=currentKI2();const distBase=cur.base?cur.user/cur.base-1:0,distDown=cur.down?cur.user/cur.down-1:0,distUp=cur.up?cur.user/cur.up-1:0;return head('USER INPUT','User Scenario Lab','Escenario editable e independiente. No reescribe Base ni actuals.')+probabilityEditor()+`<section class="kpis">${kpi('KI USER',fmt(cur.user),`vs Base ${pct(distBase)}`,'#7c3aed','USER INPUT')}${kpi('VS DOWNSIDE',pct(distDown),'distancia',COLORS.amber,'CALC')}${kpi('VS UPSIDE',pct(distUp),'distancia',COLORS.blue,'CALC')}${kpi('LIKELIHOOD',`${MASTER.userLikelihood}%`,'compatibilidad editable hasta calibración',COLORS.amber,'ASSUMPTION')}</section>`+card('Variables del laboratorio','Lo conectado modifica el escenario; lo no conectado queda explícito.',`<div class="lab-grid"><div>${mStatus('CONNECTED','green')}<b>Mercado mensual / KI</b><small>Ajuste % vs Base</small></div><div>${mStatus('PENDING','amber')}<b>Inflación / salario / tasa / FX</b><small>requiere elasticidades calibradas</small></div><div>${mStatus('PENDING','amber')}<b>Stock / supply cap</b><small>requiere USER INPUT o fuente protegida</small></div><div>${mStatus('PENDING','amber')}<b>Share Honda</b><small>versión protegida / local</small></div></div>`,'INPUT MAP')}
function renderForecastCY(){const act2026=DATA.market_history.filter(r=>r.period>='2026-01'&&r.period<='2026-09');const f=DATA.forecast.rows.filter(r=>r.period>='2026-10'&&r.period<='2026-12');const actual=sumRows(act2026);const sums={down:actual,base:actual,up:actual,user:actual};f.forEach(r=>Object.keys(sums).forEach(k=>sums[k]+=Number(r[k]||0)));return head('FORECAST CY','Forecast CY','Actual acumulado + forecast restante. CY 2026 queda totalmente reconciliado; años futuros requieren extensión mensual oficial.')+`<section class="kpis">${kpi('ACTUAL YTD',fmt(actual),`${act2026.length} meses cerrados`,COLORS.actual,'FACT')}${kpi('CY BASE',fmt(sums.base),'Ene–Dic',COLORS.red,'FORECAST')}${kpi('CY DOWN',fmt(sums.down),'Ene–Dic',COLORS.down,'FORECAST')}${kpi('CY UP',fmt(sums.up),'Ene–Dic',COLORS.blue,'FORECAST')}${kpi('CY USER',fmt(sums.user),'independiente','#7c3aed','USER INPUT')}</section>`+pendingCard('CY 2027–2035','Requiere extender el motor mensual oficial más allá de Mar-27 manteniendo la metodología histórica y backtesting.')}
function renderForecastKI(){const cur=currentKI2();return head('KI 26/27','Forecast KI actual','Abril–marzo: actuals cerrados bloqueados y meses restantes proyectados.')+`<section class="kpis">${kpi('DOWN',fmt(cur.down),'Abr–Mar',COLORS.down,'FORECAST')}${kpi('BASE',fmt(cur.base),'Abr–Mar',COLORS.red,'FORECAST')}${kpi('UP',fmt(cur.up),'Abr–Mar',COLORS.blue,'FORECAST')}${kpi('USER',fmt(cur.user),'separado','#7c3aed','USER INPUT')}${kpi('EXPECTED',fmt(cur.expected),'Down/Base/Up ponderado',COLORS.green,'ESTIMATE')}</section>`+card('Apertura mensual','Abr–Sep cerrados + Oct–Mar forecast.',storyForecastChart(),'KI 26/27')+pendingCard('Forecast anterior / error KI','Requiere archivo de versiones anteriores para medir error y cambio contra forecast previo.')}
function renderFutureKI(){return head('LONG RANGE','Próximos cinco KI','Extensión estructural del forecast. La incertidumbre se abre con el horizonte y la confianza baja progresivamente.')+kiTable()+`<div class="callout amber">${mStatus('FORECAST','amber')} KI posteriores a 26/27 son extensión estructural preliminar; deben recalibrarse cuando el motor mensual de 12+ meses y el backtesting estén integrados.</div>`}
function renderKICompare(){return head('KI COMPARATOR','Comparador KI y escenarios','Una tabla única para Actual, Down, Base, Up, User y confianza.')+kiTable()+card('Trayectoria de KI','Comparación de escenarios por año.',`<div class="empty">La visual multianual se alimenta de la misma tabla KI; la banda se ampliará al integrar intervalos de confianza calibrados.</div>`,'MULTI-KI')}
function renderMethod(){return renderData()}
function renderValidation(){return head('VALIDATION','Validación y backtesting','El forecast no cambia sin explicación. Métricas de error se publican sólo cuando existe archivo histórico de forecasts versionados.')+`<div class="grid three">${pendingCard('MAPE / MAE / RMSE','Requiere forecast histórico con fecha de emisión y actual posterior.')}${pendingCard('Bias / cobertura','Requiere distribución de errores por horizonte.')}${pendingCard('N-5 old vs nuevo','Requiere output comparable del modelo N-5 old.')}</div>`+card('Changelog','La versión vigente ya se identifica en la app.',`<div class="changelog-box"><b>${DATA.forecast?.version||'—'}</b><p>${DATA.forecast?.method||'Sin descripción adicional.'}</p></div>`,'VERSIONING')}
function renderGeography(){return head('GEO','Geografía','La hoja existe, pero no atribuye geografía a CAFAM si CAFAM no la publica.')+pendingCard('Región / provincia / red','Conectar archivo geográfico válido (SIOMAA u otra fuente identificada) con marca, modelo, segmento y fecha.')}
function renderActions(){return head('ACTION BOARD','Riesgos, oportunidades y acciones','Cada conclusión termina en una acción con gatillo y escenario.')+`<div class="grid two">${card('Riesgos','Lo que puede romper Base.',`<div class="action-list"><div><b>R1</b><span>Crédito / CFT deteriora affordability.</span></div><div><b>R2</b><span>FX traslada presión a precio y mix importado.</span></div><div><b>R3</b><span>Supply insuficiente o sobrestock desalinean patentamientos.</span></div></div>`,'RISKS')}${card('Oportunidades','Lo que puede empujar Up.',`<div class="action-list"><div><b>O1</b><span>Sustitución auto→moto por costo total.</span></div><div><b>O2</b><span>Recuperación real + financiación mejora conversión.</span></div><div><b>O3</b><span>CUB/LMC y lanzamientos pueden capturar mix.</span></div></div>`,'OPPORTUNITIES')}</div>`+card('Acciones','Responsable y fecha quedan USER INPUT hasta contar con workflow.',`<div class="table-wrap"><table class="table"><thead><tr><th>Acción</th><th>Gatillo</th><th>Escenario</th><th>Responsable</th><th>Estado</th></tr></thead><tbody><tr><td>Revisar Base</td><td>MTD fuera de banda</td><td>Todos</td><td>USER INPUT</td><td>${mStatus('PENDING','amber')}</td></tr><tr><td>Revisar affordability</td><td>CFT/precio cambia</td><td>Down/Base</td><td>USER INPUT</td><td>${mStatus('PENDING','amber')}</td></tr><tr><td>Revisar supply</td><td>Imports/ventas &lt;90%</td><td>Base/Up</td><td>USER INPUT</td><td>${mStatus('PENDING','amber')}</td></tr></tbody></table></div>`,'ACTION LOG')}
function renderMasterSheet(view){
 const map={argentina:renderArgentina,overview:renderOverview,affordability:renderAffordabilityMaster,automoto:renderAutoMoto,market:renderMarket,momentum:renderMomentum,history:renderHistory,seasonality:renderSeasonalityMaster,segments:renderSegments,competition:renderCompetition,imports:renderImports,product:renderProduct,newmodels:renderNewModels,intelligence:renderIntelligence,diagnostic:renderDiagnostic,scenarios:renderScenarios,probability:renderProbability,userlab:renderUserLab,forecast:renderForecast,forecastcy:renderForecastCY,forecastki:renderForecastKI,futureki:renderFutureKI,kicompare:renderKICompare,method:renderMethod,validation:renderValidation,honda:renderHonda,productplanning:renderProduct,geography:renderGeography,safety:renderSafety,actions:renderActions,reports:renderReports,data:renderData,updates:renderUpdates};
 return (map[view]||renderOverview)();
}
function bindMasterControls(){
 $$('.master-prob').forEach(i=>i.addEventListener('change',e=>{MASTER.probs[e.target.dataset.prob]=clamp(e.target.value,0,100);masterSave();masterRender()}));
 const ul=$('#userLikelihood');if(ul)ul.addEventListener('change',e=>{MASTER.userLikelihood=clamp(e.target.value,0,100);masterSave();masterRender()});
 $$('.weight-input').forEach(i=>i.addEventListener('change',e=>{MASTER.weights[e.target.dataset.weight]=clamp(e.target.value,0,100);masterSave();masterRender()}));
 const adj=$('#userAdj');if(adj)adj.addEventListener('input',e=>{STORY.userAdj=clamp(e.target.value,-20,20);saveStory();syncUserScenario();masterRender()});
}
function masterRender(){
 if(!DATA)return;syncUserScenario();
 if(!(state.view in TITLES))state.view='argentina';
 if(location.hash!==`#${state.view}`)history.replaceState(null,'',`#${state.view}`);
 $('#viewTitle').textContent=TITLES[state.view]||state.view;
 $('#navigation').innerHTML=masterNav();
 $('#content').innerHTML=renderMasterSheet(state.view);
 $$('#navigation button').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;masterRender()}));
 bindChartTips(); if(typeof bindViewActions==='function')bindViewActions();bindMasterControls();$('#sidebar')?.classList.remove('open');
}
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(v in TITLES&&DATA){state.view=v;masterRender()}});
(function bootMaster(){
 installMasterNav();
 const wait=setInterval(()=>{if(DATA){clearInterval(wait);const hash=location.hash.slice(1);state.view=(hash in TITLES)?hash:'argentina';masterRender()}},50);
})();
