/* Single-report engine: one coherent management flow, closed market + open month kept distinct. */
const REPORT_INDEX=[['executive','01','Resumen ejecutivo'],['context','02','Argentina hoy'],['market','03','Mercado, Daily & estacionalidad'],['structure','04','Segmentos, competencia & supply'],['consumer','05','Consumidor & movilidad'],['forecast','06','Forecast CY / KI'],['user','07','Probabilidad & User Scenario'],['planning','08','Honda & Planning'],['actions','09','Radar, riesgos & acciones'],['method','10','Metodología, validación & reportes']];
const RPROB=JSON.parse(localStorage.getItem('2w.prob')||'{"down":20,"base":60,"up":20}');
let USER_LIKE=Number(localStorage.getItem('2w.user.like')||50);
const rsum=(rows,key='value')=>(rows||[]).reduce((a,b)=>a+(Number(b?.[key])||0),0);
const rstatus=(x,t='green')=>badge(x,t);
function ptotal(){return ['down','base','up'].reduce((a,k)=>a+(Number(RPROB[k])||0),0)}
function pnormalize(){const t=ptotal();if(!t){Object.assign(RPROB,{down:20,base:60,up:20})}else{for(const k of ['down','base','up'])RPROB[k]=Math.round(RPROB[k]/t*100);RPROB.base+=100-ptotal()}localStorage.setItem('2w.prob',JSON.stringify(RPROB))}
pnormalize();probTotal=()=>ptotal();scenarioExpected=r=>Math.round(((r.down||0)*RPROB.down+(r.base||0)*RPROB.base+(r.up||0)*RPROB.up)/(ptotal()||100));
syncUserScenario=function(){if(!DATA)return;const f=1+STORY.userAdj/100;DATA.forecast.rows.forEach(r=>{r.user=Math.round(r.base*f);r.expected=scenarioExpected(r)});(DATA.forecast.segments||[]).forEach((r,i)=>{const total=DATA.forecast.rows[i]?.user||r.total.base,alloc=applyLargestRemainder(r.segments,total);r.total.user=total;r.total.expected=scenarioExpected(r.total);r.segments.forEach(s=>{s.user=alloc[s.name];s.expected=scenarioExpected(s)})});(DATA.honda?.forecast||[]).forEach(r=>{r.user=Math.round(r.base*f);r.expected=scenarioExpected(r)})};
function nav(){return REPORT_INDEX.map(([id,n,t])=>`<button data-anchor="${id}"><i>${n}</i><span>${t}</span></button>`).join('')}
function chapter(id,n,title,copy,body){return `<section id="${id}" class="single-chapter"><header><i>${n}</i><div><span>CAPÍTULO ${n}</span><h2>${title}</h2><p>${copy}</p></div></header>${body}</section>`}
function pending(title,copy){return `<div class="pending-inline">${rstatus('PENDING','amber')}<div><b>${title}</b><small>${copy}</small></div></div>`}
function openMonth(){
  const period=DATA?.live?.daily_period||DATA?.meta?.daily_period||null;
  const cutoff=DATA?.live?.daily_cutoff||DATA?.meta?.daily_cutoff||null;
  const value=Number(DATA?.live?.daily_mtd||DATA?.meta?.daily_mtd||0);
  const parts=String(period||'').split('-').map(Number),m=parts[1];
  const label=Number.isFinite(m)?`${MONTHS[m-1].toUpperCase()} MTD`:'MES ABIERTO';
  return {period,cutoff,value,label};
}
function closedLabel(){const p=String(DATA?.meta?.market_cutoff||'');const [y,m]=p.split('-').map(Number);return Number.isFinite(m)?`${MONTHS[m-1].toUpperCase()} CIERRE`:'ÚLTIMO CIERRE'}
function updateBand(){const o=openMonth();return `<div class="update-band"><div><span>CIERRE</span><b>${DATA.meta.market_cutoff}</b></div><div><span>SIOMAA</span><b>${o.cutoff||'—'}</b></div><div><span>IMPORTS</span><b>${DATA.meta.imports_cutoff||DATA.imports?.cutoff||'—'}</b></div><div><span>PRECIOS</span><b>${DATA.product_planning?.prices?.[0]?.valid_through||'—'}</b></div><div><span>FORECAST</span><b>${DATA.forecast.version}</b></div></div>`}
function exec(){const e=DATA.executive,h=DATA.honda,ki=currentKI(),cal=calendarSummary(),o=openMonth();const openK=o.value?kpi(o.label,fmt(o.value),`corte ${o.cutoff||'—'} · mes abierto`,COLORS.red,'OPEN MONTH'):kpi('MES ABIERTO','—','sin Daily validado',COLORS.amber,'PENDING');return chapter('executive','01','Resumen ejecutivo','Primero, la lectura de decisión: cierre oficial, mes abierto, KI y posición Honda sin mezclar hechos con estimaciones.',`<section class="kpis">${openK}${kpi(closedLabel(),fmt(e.market),`${pct(e.mom)} MoM · ${pct(e.yoy)} YoY`,COLORS.actual,'FACT')}${kpi('KI 26/27 EXPECTED',fmt(ki.expected),'Down/Base/Up ponderado',COLORS.green,'ESTIMATE')}${kpi('HONDA SHARE',pct(h.share),`último cierre · gap ${pp(.30-h.share)} a 30%`,COLORS.red,'FACT')}${kpi('USER',`${STORY.userAdj>=0?'+':''}${STORY.userAdj.toFixed(1)}%`,`${USER_LIKE}% likelihood`,'#7c3aed','USER INPUT')}</section><div class="storyline"><div><b>Qué pasó</b><p>El último cierre oficial mantiene una expansión fuerte; el Daily del mes abierto se lee por separado para no contaminar el histórico cerrado.</p></div><div><b>Qué lo sostiene</b><p>Movilidad económica, estacionalidad y mix; crédito, ingreso y actividad siguen siendo límites a vigilar.</p></div><div><b>Qué mirar ahora</b><p>Velocidad MTD, mix por segmento, financiación, importaciones y señales competitivas antes de mover el escenario Base.</p></div></div>`)}
function ctx(){const m=DATA.macro||[],warn=m.filter(x=>tone(x.direction)!=='green').length;return chapter('context','02','Argentina hoy','El contexto explica por qué el mercado puede acelerar o frenarse; acompaña al dato observado, no lo reemplaza.',`<div class="context-call">${rstatus(warn>2?'FRÁGIL':'FAVORABLE CON ALERTAS',warn>2?'amber':'green')}<p>Inflación, ingreso, actividad, empleo, crédito y FX se leen como drivers del forecast y de affordability.</p></div><div class="grid three">${m.slice(0,6).map(signalCard).join('')}</div><div class="pending-row">${pending('Empleo / informalidad','Completar series comparables y cortes.')}${pending('Costo auto vs moto','Conectar autos, seguro, combustible y mantenimiento.')}</div>`)}
function market(){const hist=periodRows(DATA.market_history),last=hist.at(-1),idx=(DATA.seasonality?.month_labels||MONTHS).map((_,i)=>({period:`2026-${String(i+1).padStart(2,'0')}`,idx:DATA.seasonality.market.monthly_index[i]})),o=openMonth();const r=n=>DATA.market_history.slice(-n).reduce((a,b)=>a+b.value,0)/Math.min(n,DATA.market_history.length);const openK=o.value?kpi(o.label,fmt(o.value),`SIOMAA · corte ${o.cutoff||'—'}`,COLORS.red,'OPEN MONTH'):kpi('MES ABIERTO','—','Daily no disponible',COLORS.amber,'PENDING');return chapter('market','03','Mercado actual, Daily & estacionalidad','Primero el cierre histórico; después la velocidad del mes abierto. Rolling y estacionalidad sirven como contexto, no sustituyen el Daily.',`<section class="kpis">${openK}${kpi('ROLLING 3M',fmt(r(3)),'promedio mensual cerrado',COLORS.red,'FACT')}${kpi('ROLLING 6M',fmt(r(6)),'promedio mensual cerrado',COLORS.blue,'FACT')}${kpi('ROLLING 12M',fmt(r(12)),'promedio mensual cerrado',COLORS.green,'FACT')}</section><div class="grid two">${card('Historia de mercado','Sólo meses cerrados; período controlado por filtro global.',lineChart(hist.map(x=>({...x,market:x.value})),[{key:'market',name:'Mercado',color:COLORS.actual}],{zero:true}),'HISTORY')}${card('Estacionalidad','Mediana 2010–2025 · Σ=12.',lineChart(idx,[{key:'idx',name:'Índice',color:COLORS.blue}],{zero:false,minValue:.55,maxValue:1.45}),'SEASONALITY')}</div><div class="analysis-line"><b>Último cierre:</b> ${last?.period||'—'} · régimen ${last?.yoy>0.1?'expansivo':last?.yoy<-.05?'contractivo':'neutral'} · YoY ${pct(last?.yoy)} · MoM ${pct(last?.mom)}.${o.value?` <b>Mes abierto:</b> ${o.period} · ${fmt(o.value)} acumuladas al ${o.cutoff}.`:''}</div>`)}
function structure(){const c=DATA.competition,row=DATA.segment_history?.at(-1);let segs=(row?.segments||[]).slice().sort((a,b)=>b.value-a.value);if(state.segment!=='TOTAL')segs=segs.filter(x=>x.name===state.segment);const signals=DATA.imports?.new_model_signals||[];return chapter('structure','04','Segmentos, competencia & supply','Después del total se abre el mercado: segmentos, marcas, modelos e importaciones para detectar crecimiento, amenazas y cambios de mix.',`<div class="grid two">${card('Segmentos','Filtro global de segmento aplicado.',barChart(segs.map(x=>({name:x.name,value:x.value,share:x.share})),{showShare:true,color:r=>COLORS[r.name]||COLORS.blue}),'STRUCTURE')}${card('Top 15 marcas','Último cierre disponible.',barChart(c.top_brands,{showShare:true,color:r=>COLORS[r.name]||COLORS.blue}),'COMPETITION')}</div><div class="grid two">${card('Top modelos','Ranking del último cierre disponible.',barChart(c.top_models,{showShare:true,color:r=>r.brand==='HONDA'?COLORS.red:COLORS.actual,limit:10}),'MODELS')}${card('Import pressure / amenazas','Supply se usa como señal; nunca se suma a patentamientos.',`<div class="intel-list">${signals.slice(0,6).map(x=>`<div>${rstatus('EARLY SIGNAL','amber')}<b>${x.name}</b><span>${fmt(x.units||0)} uds</span></div>`).join('')||'Sin señales cargadas'}</div>${pending('Stock terminal/dealer','Sólo con fuente confiable o USER INPUT.')}`,'SUPPLY')}</div>`)}
function consumer(){const prices=DATA.product_planning?.prices||[];return chapter('consumer','05','Consumidor & movilidad','Luego del mercado y su estructura, affordability ayuda a explicar la capacidad real de convertir intención en compra.',`<div class="grid two">${card('Precios observados','Snapshots con vigencia.',`<div class="table-wrap"><table class="table"><thead><tr><th>Modelo</th><th>Precio</th><th>Vigencia</th></tr></thead><tbody>${prices.slice(0,8).map(p=>`<tr><td>${p.model}</td><td>${p.price?money(p.price):`${money(p.price_from)} – ${money(p.price_to)}`}</td><td>${p.valid_through||'—'}</td></tr>`).join('')}</tbody></table></div>`,'FACT')}${card('Affordability & autos vs motos','No completar silenciosamente.',`${pending('Cuota/salario','Falta CFT, anticipo, plazo e ingreso alineado.')}${pending('Índice affordability','Falta serie histórica compatible.')}${pending('Autos vs motos','Falta fuente gobernante de autos del mismo mes.')}`,'DATA GAPS')}</div>`)}
function kiRows(){const prev=actualKI(2025),cur=currentKI(),growth=Number(DATA.forecast.structural_growth||.035),rows=[{ki:prev.label,actual:prev.value,conf:'ACTUAL'},{ki:cur.label,...cur,conf:'ALTA / MEDIA'}];let base=cur.base;for(let y=2027;y<=2030;y++){base=Math.round(base*(1+growth));const band=.045+.018*(y-2026),down=Math.round(base*(1-band)),up=Math.round(base*(1+band)),user=Math.round(base*(1+STORY.userAdj/100));rows.push({ki:`KI ${String(y).slice(-2)}/${String(y+1).slice(-2)}`,down,base,up,user,expected:scenarioExpected({down,base,up}),conf:y===2027?'MEDIA':'BAJA'})}return rows}
function kit(){return `<div class="table-wrap"><table class="table"><thead><tr><th>KI</th><th>Actual</th><th>Down</th><th>Base</th><th>Up</th><th>User</th><th>Expected</th><th>Conf.</th></tr></thead><tbody>${kiRows().map(r=>`<tr><td><b>${r.ki}</b></td><td>${r.actual?fmt(r.actual):'—'}</td><td>${r.down?fmt(r.down):'—'}</td><td>${r.base?fmt(r.base):'—'}</td><td>${r.up?fmt(r.up):'—'}</td><td>${r.user?fmt(r.user):'—'}</td><td>${r.expected?fmt(r.expected):r.actual?fmt(r.actual):'—'}</td><td>${r.conf}</td></tr>`).join('')}</tbody></table></div>`}
function forecast(){const rows=DATA.forecast.rows,act=DATA.market_history.filter(r=>r.period>='2026-01'&&r.period<='2026-09'),cy={down:rsum(act),base:rsum(act),up:rsum(act),user:rsum(act)};rows.filter(r=>r.period<='2026-12').forEach(r=>Object.keys(cy).forEach(k=>cy[k]+=Number(r[k]||0)));return chapter('forecast','06','Forecast mensual, CY & KI','Actuals cerrados permanecen bloqueados. El mes abierto informa el forecast, pero no se convierte en Actual hasta el cierre.',`<div class="grid two">${card('Mensual Oct-26 → Mar-27','Down/Base/Up/User simultáneos.',lineChart(rows,[{key:'down',name:'Down',color:COLORS.down},{key:'base',name:'Base',color:COLORS.red},{key:'up',name:'Up',color:COLORS.blue},{key:'user',name:'User',color:'#7c3aed'}],{zero:true}),'MONTHLY')}${card('CY 2026','Actual cerrado + forecast restante.',`<div class="scenario-strip"><span>Down <b>${fmt(cy.down)}</b></span><span>Base <b>${fmt(cy.base)}</b></span><span>Up <b>${fmt(cy.up)}</b></span><span>User <b>${fmt(cy.user)}</b></span></div>`,'CY')}</div>${kit()}<div class="note">Los KI posteriores a 26/27 son extensión estructural preliminar; la banda se abre con horizonte y debe recalibrarse con backtesting y motor mensual.</div>`)}
function userBlock(){return chapter('user','07','Probabilidad, posibilidad & User Scenario','Down + Base + Up = 100%. User queda separado para comparar el plan interno contra un outlook independiente.',`<div class="user-panel"><div><span>User vs Base</span><b>${STORY.userAdj>=0?'+':''}${STORY.userAdj.toFixed(1)}%</b><input id="uAdj" type="range" min="-20" max="20" step="0.5" value="${STORY.userAdj}"></div><div class="prob-grid">${['down','base','up'].map(k=>`<label>${k}<input class="pInput" data-p="${k}" type="number" min="0" max="100" value="${RPROB[k]}"><small>%</small></label>`).join('')}<label>User likelihood<input id="uLike" type="number" min="0" max="100" value="${USER_LIKE}"><small>%</small></label></div><div class="prob-total ${ptotal()===100?'ok':'bad'}"><span>Down + Base + Up</span><b>${ptotal()}%</b></div></div><div class="grid two">${card('Ponderación inicial','ASSUMPTION hasta backtesting.',`<div class="weights">Mercado/momentum 25% · Macro/consumidor 20% · Affordability/crédito 20% · Estacionalidad 10% · Supply 10% · Producto/competencia 10% · Política/regulación 5%</div>`,'ASSUMPTION')}${card('Posibilidad operativa','No declarar imposible sin restricciones físicas.',`${pending('Supply cap / stock','Falta fuente o USER INPUT.')}${pending('Percentil / distribución','Falta backtesting calibrado.')}`,'FEASIBILITY')}</div>`)}
function planning(){const h=DATA.honda;return chapter('planning','08','Honda & Planning','La posición Honda se compara contra el outlook de mercado; el target comercial nunca modifica el forecast independiente.',`<section class="kpis">${kpi('HONDA · ÚLTIMO CIERRE',fmt(h.volume),'unidades',COLORS.red,'FACT')}${kpi('SHARE',pct(h.share),'último cierre',COLORS.red,'FACT')}${kpi('TARGET 2030','30%','trayectoria objetivo',COLORS.red,'TARGET')}${kpi('PLAN INTERNO','USER INPUT','protegido',COLORS.amber,'USER INPUT')}</section><div class="grid two">${card('Trayectoria al 30%','Gap visible.',lineChart(h.target_path.map(x=>({period:`${x.year}-12`,share:x.target_share})),[{key:'share',name:'Target',color:COLORS.red}],{percent:true,zero:true,maxValue:.32}),'COMMERCIAL')}${card('Portfolio Honda','Volumen por modelo.',barChart(h.models.slice(0,10).map(x=>({name:x.model,value:x.value,share:x.share_honda})),{showShare:true,color:COLORS.red,limit:10}),'PRODUCT')}</div>${pending('WS / RS / stock / presupuesto','Sólo en versión protegida o USER INPUT.')}`)}
function actions(){return chapter('actions','09','Radar, riesgos & acciones','El reporte termina en gatillos concretos: qué puede mover Base, qué amenaza el mix y qué señales requieren seguimiento.',`<div class="grid two">${card('Riesgos / oportunidades','Gatillos de escenario.',`<div class="action-list"><div><b>R1</b><span>Crédito/CFT deteriora affordability.</span></div><div><b>R2</b><span>FX o costos importados presionan precio.</span></div><div><b>O1</b><span>Sustitución auto→moto sostiene movilidad económica.</span></div><div><b>O2</b><span>Salario + financiación mejoran conversión.</span></div></div>`,'DECISION')}${card('Radar a monitorear','Señales que deben validarse antes de cambiar forecast.',`<div class="action-list"><div><b>01</b><span>Daily MTD versus banda esperada y mismas fechas comparables.</span></div><div><b>02</b><span>Outsiders por segmento, nuevos modelos y aceleración de share.</span></div><div><b>03</b><span>Importaciones, origen, IKD/CBU y presión de abastecimiento.</span></div><div><b>04</b><span>Financiación, precios, macro, regulación y noticias relevantes.</span></div></div>`,'INTELLIGENCE')}</div><div class="action-table"><span>Revisar Base si MTD sale de banda · Responsable: USER INPUT</span><span>Revisar affordability si cambia CFT/precio · Responsable: USER INPUT</span><span>Revisar supply si imports/ventas se deteriora · Responsable: USER INPUT</span></div>${pending('Geografía','Conectar fuente válida; no atribuir geografía a CAFAM si la fuente no la publica.')}`)}
function method(){const meta=DATA.seasonality.metadata;return chapter('method','10','Metodología, validación & reportes','Cierre: cómo se calcula, qué está observado, qué es estimado y cómo se exporta.',`<div class="grid two">${card('Motor vigente','Metodología trabajada, no un modelo distinto.',`<div class="formula">Nivel desestacionalizado = MEDIANA(mercado / índice, 6M)<br><br>Crecimiento(h) = 3,5% + (YoY reciente − 3,5%) × 0,68ʰ<br><br>Base = nivel × estacionalidad × crecimiento<br><br>Down/Up = banda creciente</div><small>${DATA.forecast.method}</small>`,'METHOD')}${card('QA','Controles antes de publicar.',`<div class="action-list"><div><b>✓</b><span>Estacionalidad Σ=12 · ${meta.available_history}</span></div><div><b>✓</b><span>Segmentos reconciliados por largest remainder.</span></div><div><b>✓</b><span>Cierre oficial separado de mes abierto.</span></div><div><b>!</b><span>CAFAM vs Pivot visible.</span></div></div>`,'CONTROL')}</div><div class="grid two">${card('Backtesting','No inventar precisión.',`${pending('MAPE / MAE / RMSE / Bias','Requiere histórico de forecasts versionados.')}${pending('N-5 old vs nuevo','Requiere output comparable.')}`,'VALIDATION')}${card('Exportar','Misma evidencia, distintos formatos.',`<div class="export-actions"><button data-export="pdf">PDF</button><button data-export="ppt">PowerPoint</button><button data-export="csv">Excel / CSV</button></div>`,'REPORTS')}</div>`)}
function full(){return `<div class="report-cover"><span>2W MARKET ANALYSIS · ARGENTINA</span><h1>Argentina Motorcycle Intelligence</h1><p>Resumen → contexto → mercado cerrado + Daily → estructura → consumidor → forecast → Honda → acciones.</p></div>${updateBand()}${exec()}${ctx()}${market()}${structure()}${consumer()}${forecast()}${userBlock()}${planning()}${actions()}${method()}`}
function bindSingle(){$$('#navigation [data-anchor]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.anchor)?.scrollIntoView({behavior:'smooth',block:'start'});$('#sidebar')?.classList.remove('open')});const a=$('#uAdj');if(a)a.oninput=e=>{STORY.userAdj=clamp(e.target.value,-20,20);saveStory();syncUserScenario();render()};$$('.pInput').forEach(i=>i.onchange=e=>{RPROB[e.target.dataset.p]=clamp(e.target.value,0,100);localStorage.setItem('2w.prob',JSON.stringify(RPROB));syncUserScenario();render()});const l=$('#uLike');if(l)l.onchange=e=>{USER_LIKE=clamp(e.target.value,0,100);localStorage.setItem('2w.user.like',String(USER_LIKE));render()};$$('[data-export]').forEach(b=>b.onclick=()=>exportReport(b.dataset.export));bindChartTips()}
let robs=null;function observe(){if(robs)robs.disconnect();if(!('IntersectionObserver'in window))return;robs=new IntersectionObserver(es=>{const e=es.find(x=>x.isIntersecting);if(e)$$('#navigation [data-anchor]').forEach(b=>b.classList.toggle('active',b.dataset.anchor===e.target.id))},{rootMargin:'-25% 0px -65% 0px'});$$('.single-chapter').forEach(s=>robs.observe(s))}
render=function(){if(!DATA)return;syncUserScenario();$('#viewTitle').textContent='Reporte integral';$('#navigation').innerHTML=nav();$('#content').innerHTML=full();bindSingle();observe();$('#sidebar')?.classList.remove('open')};
setTimeout(()=>{if(DATA)render()},0);