function renderOverview(){
  const e=DATA.executive,forecast=DATA.forecast.rows[0],marketRows=marketSeries(),cal=calendarSummary(),h=DATA.honda;
  const macroRisks=DATA.macro.filter(item=>tone(item.direction)!=="green").length;
  return head("DECISION DESK","Argentina y el mercado de motos, en una lectura",e.summary,{tone:"amber",text:e.signal})+
  `<section class="kpis">${kpi("MERCADO SEP",fmt(e.market),`${DATA.meta.market_cutoff} · CAFAM`,COLORS.actual,"ACTUAL")}${kpi("VARIACIÓN MOM",pct(e.mom),"contra mes anterior",e.mom>0?COLORS.green:COLORS.red)}${kpi("VARIACIÓN YOY",pct(e.yoy),"contra Sep-25",COLORS.green)}${kpi("HONDA SHARE",pct(h.share),`${fmt(h.volume)} uds · objetivo 30% 2030`,COLORS.red)}${kpi(cal.label,fmt(cal.value),`${cal.months} meses · ${state.scenario.toUpperCase()}`,COLORS.blue)}</section>`+
  `<div class="grid two">${card("Mercado observado + forecast","Actual hasta Sep-26; desde Oct-26 responde al escenario global.",lineChart(marketRows,[{key:"actual",name:"Actual",color:COLORS.actual},{key:"forecast",name:`Forecast ${state.scenario}`,color:COLORS[state.scenario]}],{zero:true}),"MERCADO TOTAL")}
  <section class="card analysis"><div class="score">72</div><div><span class="eyebrow">LECTURA AUTOMÁTICA</span><h3>Demanda alta, pero con costo de crédito y actividad bajo observación</h3><p>Septiembre cerró por encima de agosto y del año anterior. El escenario Base mantiene expansión con convergencia; la estacionalidad favorece octubre pero no justifica extrapolar el último YoY de forma lineal. Honda lidera, aunque la brecha al 30% 2030 sigue siendo material.</p><div class="decision-tags">${badge("MERCADO ↑","green")}${badge("CRÉDITO","amber")}${badge("HONDA 20,5%","amber")}</div></div></section></div>`+
  `<div class="grid three">${DATA.macro.slice(0,3).map(signalCard).join("")}</div>`+
  card("Qué cambió y qué mirar ahora","Síntesis operativa para la próxima decisión.",`<div class="decision-grid"><div><b>1</b><h3>CUB vuelve a concentrar la pelea competitiva</h3><p>Wave, Smash, KN110-8, B110 y Energy dominan el ranking por modelo. La llegada de Biz amplía el frente competitivo dentro de Honda.</p></div><div><b>2</b><h3>Honda necesita más que sostener share</h3><p>El 30% 2030 se muestra como trayectoria objetivo separada del forecast de mercado. No se fuerza el mercado para cerrar un target.</p></div><div><b>3</b><h3>Importaciones son señal de oferta</h3><p>Se monitorean por modelo/marca como presión futura, sin sumarlas a patentamientos.</p></div></div>`,"NEXT ACTIONS");
}

function signalCard(item){const t=tone(item.direction),colors={green:COLORS.green,amber:COLORS.amber,red:COLORS.red};return `<article class="card signal-card"><div class="signal-top"><span class="eyebrow">${item.date}</span><span class="badge ${t}">${t==="green"?"FAVORABLE":t==="red"?"ALERTA":"ATENCIÓN"}</span></div><h3>${item.metric}</h3><b class="signal-value">${item.value}</b><p>${item.detail}</p><div class="bar"><i style="width:${t==="green"?78:t==="amber"?52:28}%;background:${colors[t]}"></i></div></article>`}

function renderArgentina(){
  const priceCount=DATA.product_planning?.prices?.length||0;
  return head("MACRO · MICRO · AFFORDABILITY","¿Cómo está Argentina hoy?","Contexto que condiciona ingreso, crédito, precio y decisión de compra. Cada señal conserva corte y fuente.")+
  `<div class="grid three">${DATA.macro.map(signalCard).join("")}</div>`+
  `<div class="grid two">${card("Transmisión a demanda de motos","Qué variables pueden impulsar o frenar conversión.",`<div class="signals"><div class="signal"><div class="signal-top"><h3>Ingreso nominal vs inflación</h3>${badge("MEJORA INCIPIENTE","green")}</div><p>El ingreso nominal mejora contra la inflación, pero el análisis real exige alinear el mismo período antes de concluir recuperación plena.</p></div><div class="signal"><div class="signal-top"><h3>Crédito minorista</h3>${badge("ALERTA","red")}</div><p>La cuota efectiva sigue siendo decisiva: cambios en tasa o desaparición de tasa cero pueden modificar mix y conversión sin que cambie la necesidad de movilidad.</p></div><div class="signal"><div class="signal-top"><h3>Actividad y empleo</h3>${badge("MONITOREAR","amber")}</div><p>El mercado de motos puede desacoplarse de la actividad por sustitución de movilidad, pero ese desacople no se proyecta indefinidamente.</p></div></div>`,"TRANSMISIÓN")}${card("Affordability por modelo","Framework ya conectado a precio + macro; no mezcla cortes.",`<div class="affordability-grid">${DATA.product_planning.prices.slice(0,6).map(p=>`<div class="aff-card"><span>${p.model}</span><b>${p.price?money(p.price):`${money(p.price_from)} – ${money(p.price_to)}`}</b><small>último oficial · hasta ${p.valid_through}</small></div>`).join("")}</div><div class="callout amber"><b>Regla:</b> precio y salario deben compartir corte antes de calcular meses de salario o cuota/ingreso. ${priceCount} modelos ya tienen snapshot oficial.</div>`,"AFFORDABILITY")}</div>`+
  card("Micro señales del mercado","Patentamientos, origen y financiación.",`<div class="grid three compact">${DATA.micro.map(signalCard).join("")}</div>`,"MICRO / MOTOS");
}

function renderMarket(){
  const history=periodRows(DATA.market_history),growth=history.filter(row=>row.yoy!==null),rows=history.map(row=>({...row,actual:row.value})),cal=calendarSummary();
  return head("MERCADO TOTAL · CAFAM + PIVOT","Evolución del mercado argentino","CAFAM gobierna el cierre vigente. Pivot aporta profundidad histórica. Las diferencias de fuente se muestran y no se corrigen en silencio.")+
  `<section class="kpis">${kpi("ÚLTIMO CIERRE",fmt(DATA.executive.market),DATA.meta.market_cutoff,COLORS.actual)}${kpi(cal.label,fmt(cal.value),`${state.calendar} · ${state.scenario}`,COLORS.blue)}${kpi("PIVOT SEP",fmt(DATA.executive.pivot_latest),"referencia estructural",COLORS.purple||"#8a5bd1")}${kpi("GAP FUENTES",fmt(DATA.executive.source_gap),"Pivot − CAFAM",COLORS.amber)}${kpi("HISTÓRICO",`${DATA.market_history.length} meses`,`${DATA.market_history[0].period} → ${DATA.meta.market_cutoff}`,COLORS.green)}</section>`+
  `<div class="grid two">${card("Patentamientos mensuales","Volumen observado según período seleccionado.",lineChart(rows,[{key:"actual",name:"Mercado",color:COLORS.actual}],{zero:true}),"EVOLUCIÓN")}${card("Crecimiento interanual","Variación contra el mismo mes del año anterior.",lineChart(growth,[{key:"yoy",name:"YoY",color:COLORS.blue}],{percent:true,zero:false,minValue:Math.min(-.5,...growth.map(x=>x.yoy||0)),maxValue:Math.max(.6,...growth.map(x=>x.yoy||0))}),"YOY")}</div>`+
  card("Últimos cierres","Detalle con comparación mensual e interanual.",tableMarket(history.slice(-18)),"TABLA GOBERNADA");
}
function tableMarket(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Mes</th><th>Fuente</th><th>Mercado</th><th>MoM</th><th>YoY</th><th>Status</th></tr></thead><tbody>${rows.slice().reverse().map(row=>`<tr><td><strong>${label(row.period)}</strong></td><td>${row.source}</td><td>${fmt(row.value)}</td><td class="${ratioTone(row.mom)}-txt">${pct(row.mom)}</td><td class="${ratioTone(row.yoy)}-txt">${pct(row.yoy)}</td><td>${badge("ACTUAL","green")}</td></tr>`).join("")}</tbody></table></div>`}

function renderCompetition(){
  const c=DATA.competition,brandMax=Math.max(...c.top_brands.map(x=>x.value));
  const brandSeries=Object.keys(c.brand_history.at(-1)||{}).filter(k=>k!=="period").map((b,i)=>({key:b,name:b,color:COLORS[b]||[COLORS.blue,COLORS.green,COLORS.amber,"#8a5bd1","#6b7280"][i%5]}));
  const maxHistory=maxOf(c.brand_history,brandSeries.map(s=>s.key));
  return head("COMPETITION INTELLIGENCE","Quién gana, con qué modelo y con qué productividad","Ranking actual Sep-26 por CAFAM. Grupos y productividad usan el último corte estructural disponible y quedan fechados por separado.",{tone:"green",text:"SEP 2026"})+
  `<section class="kpis">${kpi("HONDA #1",fmt(c.top_brands[0].value),pct(c.top_brands[0].share),COLORS.red)}${kpi("TOP 5 SHARE",pct(c.top_brands.slice(0,5).reduce((a,b)=>a+b.share,0)),"concentración Sep-26",COLORS.blue)}${kpi("MODELO #1",c.top_models[0].model,`${fmt(c.top_models[0].value)} uds`,COLORS.red)}${kpi("GRUPO #1",c.top_groups[0].name,`${fmt(c.top_groups[0].value)} · corte ${c.structure_cutoff}`,COLORS.amber)}${kpi("MEJOR PRODUCTIVIDAD",[...c.active_productivity].sort((a,b)=>b.productivity-a.productivity)[0].brand,`${fmt([...c.active_productivity].sort((a,b)=>b.productivity-a.productivity)[0].productivity)} uds/modelo`,COLORS.green)}</section>`+
  `<div class="grid two">${card("Top 15 marcas","Cierre Sep-26, share sobre mercado total.",barChart(c.top_brands,{max:brandMax,showShare:true,color:r=>COLORS[r.name]||COLORS.blue}),"CAFAM")}${card("Top 15 modelos","Ranking actual por patentamientos.",barChart(c.top_models,{showShare:true,color:r=>r.brand==="HONDA"?COLORS.red:COLORS.actual}),"MODELOS")}</div>`+
  `<div class="grid two">${card("Evolución Top 6 marcas","Escala única de volumen para comparar trayectorias.",lineChart(c.brand_history,brandSeries,{zero:true,maxValue:maxHistory}),"24 MESES")}${card("Grupos empresarios","Estructura agregada, último corte disponible.",barChart(c.top_groups,{showShare:true,color:COLORS.amber}),`CORTE ${c.structure_cutoff}`)}</div>`+
  card("Modelos activos y productividad","Más modelos no implica necesariamente más volumen por producto.",`<div class="table-wrap"><table class="table"><thead><tr><th>Marca</th><th>Volumen</th><th>Modelos activos</th><th>Uds/modelo</th><th>Lectura</th></tr></thead><tbody>${c.active_productivity.slice(0,15).map(r=>`<tr><td><strong>${r.brand}</strong></td><td>${fmt(r.volume)}</td><td>${r.active_models}</td><td>${fmt(r.productivity)}</td><td>${r.productivity>600?badge("ALTA","green"):r.productivity>300?badge("MEDIA","amber"):badge("BAJA","red")}</td></tr>`).join("")}</tbody></table></div>`,"PORTFOLIO PRODUCTIVITY");
}

function renderForecast(){
  const rows=DATA.forecast.rows.map(row=>({...row,selected:row[state.scenario]})),selected=rows.map(r=>r.selected);
  return head("FORECAST · 6 MESES","Proyección independiente y auditable","El escenario global cambia todos los números vinculados al forecast. Honda y targets comerciales no modifican el mercado proyectado.",{tone:"green",text:DATA.forecast.version})+
  `<section class="kpis">${kpi("OCT-26",fmt(rows[0].selected),state.scenario.toUpperCase(),COLORS[state.scenario])}${kpi("BASE OCT",fmt(rows[0].base),`Down ${fmt(rows[0].down)} / Up ${fmt(rows[0].up)}`,COLORS.red)}${kpi("CRECIMIENTO RECIENTE",pct(DATA.forecast.recent_yoy_median),"mediana YoY últimos 6 meses",COLORS.green)}${kpi("CREC. ESTRUCTURAL",pct(DATA.forecast.structural_growth),"convergencia de largo plazo",COLORS.blue)}${kpi("PICO ESCENARIO",fmt(Math.max(...selected)),label(rows.find(r=>r.selected===Math.max(...selected)).period),"#8a5bd1")}</section>`+
  `<div class="grid two">${card("Bandas de forecast","Downside, Base y Upside con incertidumbre creciente.",lineChart(rows,[{key:"down",name:"Downside",color:COLORS.down},{key:"base",name:"Base",color:COLORS.base},{key:"up",name:"Upside",color:COLORS.up}],{zero:true,maxValue:Math.max(...rows.map(r=>r.up))*1.08}),"ESCENARIOS")}${card("Estacionalidad mercado total","Índice robusto; Σ 12 meses = 12.",lineChart(DATA.seasonality.month_labels.map((name,index)=>({period:`2026-${String(index+1).padStart(2,"0")}`,index:DATA.seasonality.market.monthly_index[index]})),[{key:"index",name:"Índice",color:COLORS.blue}],{zero:false,minValue:.65,maxValue:1.35}),"2010–2025 + VALIDACIÓN 2026")}</div>`+
  card("Forecast mes a mes","Cada fila mantiene escenario, estacionalidad y señal de tendencia.",`<div class="table-wrap"><table class="table"><thead><tr><th>Mes</th><th>Downside</th><th>Base</th><th>Upside</th><th>Índice est.</th><th>Señal anual</th></tr></thead><tbody>${rows.map(row=>`<tr><td><strong>${label(row.period)}</strong></td><td>${fmt(row.down)}</td><td><strong>${fmt(row.base)}</strong></td><td>${fmt(row.up)}</td><td>${row.seasonal_index.toFixed(3)}</td><td>${pct(row.annual_growth_signal)}</td></tr>`).join("")}</tbody></table></div>`,"DETALLE");
}

function renderSegments(){
  const names=state.segment==="TOTAL"?["CUB","LMC","SC","FUN","ATV","OTHERS"]:[state.segment];
  const history=periodRows(DATA.segment_history).map(row=>{const out={period:row.period};row.segments.forEach(item=>out[item.name]=item.value);return out});
  const series=names.map(name=>({key:name,name,color:COLORS[name]}));
  const forecast=DATA.forecast.segments;
  const sharedMax=maxOf(history,["CUB","LMC","SC","FUN","ATV","OTHERS"]);
  const tx=DATA.segment_taxonomies,taxRows=state.taxonomy==="segment1"?tx.segment1:tx.segment2,taxHist=state.taxonomy==="segment1"?tx.segment1_history:tx.segment2_history;
  const taxNames=taxRows.slice(0,6).map(x=>x.name);const taxSeries=taxNames.map((n,i)=>({key:n,name:n,color:[COLORS.red,COLORS.blue,COLORS.green,COLORS.amber,"#8a5bd1","#6b7280"][i]}));
  return head("SEGMENT INTELLIGENCE","Management + Segmento 1 + Segmento 2, sin mezclar taxonomías","Cada familia mantiene su propia definición. El forecast Management reconcilia exactamente contra el total mensual.")+
  `<div class="taxonomy-switch"><button class="tax-btn ${state.taxonomy==="segment1"?"active":""}" data-tax="segment1">Segmento 1</button><button class="tax-btn ${state.taxonomy==="segment2"?"active":""}" data-tax="segment2">Segmento 2</button><span>Corte estructural ${tx.cutoff}</span></div>`+
  `<div class="grid two">${card("Management segments","Misma escala máxima para comparación rápida.",lineChart(history,series,{zero:true,maxValue:sharedMax}),"CUB / LMC / SC / FUN / ATV")}${card(`${state.taxonomy==="segment1"?"Segmento 1":"Segmento 2"} · evolución`,`Taxonomía alternativa separada del Management.`,lineChart(taxHist,taxSeries,{zero:true,maxValue:maxOf(taxHist,taxNames)}),"TAXONOMÍA")}</div>`+
  `<div class="grid two">${card("Ranking taxonomía","Share dentro de la taxonomía seleccionada.",barChart(taxRows,{showShare:true,color:COLORS.blue}),state.taxonomy.toUpperCase())}${card("Estacionalidad Management","Curvas robustas por familia.",lineChart(DATA.seasonality.month_labels.map((_,index)=>{const row={period:`2026-${String(index+1).padStart(2,"0")}`};names.forEach(name=>row[name]=DATA.seasonality.management[name].monthly_index[index]);return row}),series,{zero:false,minValue:.55,maxValue:1.45}),"ESTACIONALIDAD")}</div>`+
  card("Forecast segmentado","Largest remainder: suma exacta al escenario total.",`<div class="table-wrap"><table class="table"><thead><tr><th>Segmento</th>${forecast.map(row=>`<th>${label(row.period)}</th>`).join("")}</tr></thead><tbody>${names.map(name=>`<tr><td><strong>${name}</strong></td>${forecast.map(row=>`<td>${fmt(row.segments.find(item=>item.name===name)?.[state.scenario])}</td>`).join("")}</tr>`).join("")}<tr class="total-row"><td><strong>TOTAL ${state.scenario.toUpperCase()}</strong></td>${forecast.map(row=>`<td><strong>${fmt(row.total[state.scenario])}</strong></td>`).join("")}</tr></tbody></table></div>`,"RECONCILIACIÓN EXACTA");
}
